
/******************************************************************************
*
*   FILE
*   ----
*   Alternative.c
*
*   History
*   -------
*   2016-08-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_STRING sosx_Alternative_name_get(
    OV_INSTPTR_sosx_Alternative          pobj
) {
    return pobj->v_name;
}

OV_DLLFNCEXPORT OV_RESULT sosx_Alternative_name_set(
    OV_INSTPTR_sosx_Alternative          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_name,value);
}

OV_DLLFNCEXPORT OV_RESULT sosx_Alternative_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_Alternative pinst = Ov_StaticPtrCast(sosx_Alternative, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

