
/******************************************************************************
*
*   FILE
*   ----
*   BaseElement.c
*
*   History
*   -------
*   2016-08-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_TIME* sosx_BaseElement_validFrom_get(
    OV_INSTPTR_sosx_BaseElement          pobj
) {
    return &pobj->v_validFrom;
}

OV_DLLFNCEXPORT OV_RESULT sosx_BaseElement_validFrom_set(
    OV_INSTPTR_sosx_BaseElement          pobj,
    const OV_TIME*  value
) {
    pobj->v_validFrom = *value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_TIME* sosx_BaseElement_validUntil_get(
    OV_INSTPTR_sosx_BaseElement          pobj
) {
    return &pobj->v_validUntil;
}

OV_DLLFNCEXPORT OV_RESULT sosx_BaseElement_validUntil_set(
    OV_INSTPTR_sosx_BaseElement          pobj,
    const OV_TIME*  value
) {
    pobj->v_validUntil = *value;
    return OV_ERR_OK;
}

