
/******************************************************************************
*
*   FILE
*   ----
*   executeSimulation.c
*
*   History
*   -------
*   2016-08-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_STRING sosx_executeSimulation_lastFileName_get(
    OV_INSTPTR_sosx_executeSimulation          pobj
) {
    return pobj->v_lastFileName;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_lastFileName_set(
    OV_INSTPTR_sosx_executeSimulation          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_lastFileName,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_executeSimulation_simCmd_get(
    OV_INSTPTR_sosx_executeSimulation          pobj
) {
    return pobj->v_simCmd;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_simCmd_set(
    OV_INSTPTR_sosx_executeSimulation          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_simCmd,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_executeSimulation_CeaxOutFolder_get(
    OV_INSTPTR_sosx_executeSimulation          pobj
) {
    return pobj->v_CeaxOutFolder;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_CeaxOutFolder_set(
    OV_INSTPTR_sosx_executeSimulation          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_CeaxOutFolder,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_executeSimulation_SimFolder_get(
    OV_INSTPTR_sosx_executeSimulation          pobj
) {
    return pobj->v_SimFolder;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_SimFolder_set(
    OV_INSTPTR_sosx_executeSimulation          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_SimFolder,value);
}

OV_DLLFNCEXPORT void sosx_executeSimulation_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_executeSimulation pinst = Ov_StaticPtrCast(sosx_executeSimulation, pfb);

    return;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_executeSimulation pinst = Ov_StaticPtrCast(sosx_executeSimulation, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = fb_functionblock_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

