
/******************************************************************************
*
*   FILE
*   ----
*   exportCaexFb.c
*
*   History
*   -------
*   2016-08-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_STRING sosx_exportCaexFb_target_get(
    OV_INSTPTR_sosx_exportCaexFb          pobj
) {
    return pobj->v_target;
}

OV_DLLFNCEXPORT OV_RESULT sosx_exportCaexFb_target_set(
    OV_INSTPTR_sosx_exportCaexFb          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_target,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_exportCaexFb_source_get(
    OV_INSTPTR_sosx_exportCaexFb          pobj
) {
    return pobj->v_source;
}

OV_DLLFNCEXPORT OV_RESULT sosx_exportCaexFb_source_set(
    OV_INSTPTR_sosx_exportCaexFb          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_source,value);
}

OV_DLLFNCEXPORT void sosx_exportCaexFb_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_exportCaexFb pinst = Ov_StaticPtrCast(sosx_exportCaexFb, pfb);

    return;
}

OV_DLLFNCEXPORT OV_RESULT sosx_exportCaexFb_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_exportCaexFb pinst = Ov_StaticPtrCast(sosx_exportCaexFb, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = fb_functionblock_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

