
/******************************************************************************
*
*   FILE
*   ----
*   FileMonitor.c
*
*   History
*   -------
*   2016-08-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_RESULT sosx_FileMonitor_filePath_set(
    OV_INSTPTR_sosx_FileMonitor          pobj,
    const OV_STRING*  value,
    const OV_UINT veclen
) {
    return Ov_SetDynamicVectorValue(&pobj->v_filePath,value,veclen,STRING);
}

OV_DLLFNCEXPORT OV_UINT* sosx_FileMonitor_hasChanged_get(
    OV_INSTPTR_sosx_FileMonitor          pobj,
    OV_UINT *pveclen
) {
    *pveclen = pobj->v_hasChanged.veclen;
    return pobj->v_hasChanged.value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_FileMonitor_hasChanged_set(
    OV_INSTPTR_sosx_FileMonitor          pobj,
    const OV_UINT*  value,
    const OV_UINT veclen
) {
    return Ov_SetDynamicVectorValue(&pobj->v_hasChanged,value,veclen,UINT);
}

OV_DLLFNCEXPORT OV_RESULT sosx_FileMonitor_reset_set(
    OV_INSTPTR_sosx_FileMonitor          pobj,
    const OV_BOOL*  value,
    const OV_UINT veclen
) {
    return Ov_SetDynamicVectorValue(&pobj->v_reset,value,veclen,BOOL);
}

OV_DLLFNCEXPORT OV_RESULT sosx_FileMonitor_execute_set(
    OV_INSTPTR_sosx_FileMonitor          pobj,
    const OV_BOOL  value
) {
    pobj->v_execute = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_FileMonitor_exCycTime_set(
    OV_INSTPTR_sosx_FileMonitor          pobj,
    const OV_TIME_SPAN*  value
) {
    pobj->v_exCycTime = *value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT void sosx_FileMonitor_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_FileMonitor pinst = Ov_StaticPtrCast(sosx_FileMonitor, pfb);

    return;
}

OV_DLLFNCEXPORT OV_RESULT sosx_FileMonitor_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_FileMonitor pinst = Ov_StaticPtrCast(sosx_FileMonitor, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = fb_functionblock_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

