
/******************************************************************************
*
*   FILE
*   ----
*   getKsVal.c
*
*   History
*   -------
*   2016-08-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_STRING sosx_getKsVal_host_get(
    OV_INSTPTR_sosx_getKsVal          pobj
) {
    return pobj->v_host;
}

OV_DLLFNCEXPORT OV_RESULT sosx_getKsVal_host_set(
    OV_INSTPTR_sosx_getKsVal          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_host,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_getKsVal_server_get(
    OV_INSTPTR_sosx_getKsVal          pobj
) {
    return pobj->v_server;
}

OV_DLLFNCEXPORT OV_RESULT sosx_getKsVal_server_set(
    OV_INSTPTR_sosx_getKsVal          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_server,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_getKsVal_path_get(
    OV_INSTPTR_sosx_getKsVal          pobj
) {
    return pobj->v_path;
}

OV_DLLFNCEXPORT OV_RESULT sosx_getKsVal_path_set(
    OV_INSTPTR_sosx_getKsVal          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_path,value);
}

OV_DLLFNCEXPORT OV_BOOL sosx_getKsVal_doReset_get(
    OV_INSTPTR_sosx_getKsVal          pobj
) {
    return pobj->v_doReset;
}

OV_DLLFNCEXPORT OV_RESULT sosx_getKsVal_doReset_set(
    OV_INSTPTR_sosx_getKsVal          pobj,
    const OV_BOOL  value
) {
    pobj->v_doReset = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_INT sosx_getKsVal_state_get(
    OV_INSTPTR_sosx_getKsVal          pobj
) {
    return pobj->v_state;
}

OV_DLLFNCEXPORT OV_RESULT sosx_getKsVal_state_set(
    OV_INSTPTR_sosx_getKsVal          pobj,
    const OV_INT  value
) {
    pobj->v_state = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_getKsVal_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_getKsVal pinst = Ov_StaticPtrCast(sosx_getKsVal, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = fb_functionblock_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

OV_DLLFNCEXPORT void sosx_getKsVal_startup(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_getKsVal pinst = Ov_StaticPtrCast(sosx_getKsVal, pobj);

    /* do what the base class does first */
    fb_functionblock_startup(pobj);

    /* do what */


    return;
}

OV_DLLFNCEXPORT OV_RESULT sosx_getKsVal_resetall(
		OV_INSTPTR_ov_domain				pRoot
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_getKsVal_stopall(
		OV_INSTPTR_ov_domain				pRoot
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_getKsVal_startall(
		OV_INSTPTR_ov_domain				pRoot,
		OV_INT								*count
) {

    return OV_ERR_OK;
}

