
/******************************************************************************
*
*   FILE
*   ----
*   getVar.c
*
*   History
*   -------
*   2016-08-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_ANY* sosx_getVar_receivedVar_get(
    OV_INSTPTR_sosx_getVar          pobj
) {
    return &pobj->v_receivedVar;
}

OV_DLLFNCEXPORT OV_RESULT sosx_getVar_receivedVar_set(
    OV_INSTPTR_sosx_getVar          pobj,
    const OV_ANY*  value
) {
    return ov_variable_setanyvalue(&pobj->v_receivedVar, value);
}

OV_DLLFNCEXPORT OV_RESULT sosx_getVar_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_getVar pinst = Ov_StaticPtrCast(sosx_getVar, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = sosx_getKsVal_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

OV_DLLFNCEXPORT void sosx_getVar_startup(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_getVar pinst = Ov_StaticPtrCast(sosx_getVar, pobj);

    /* do what the base class does first */
    sosx_getKsVal_startup(pobj);

    /* do what */


    return;
}

OV_DLLFNCEXPORT void sosx_getVar_typemethod(
	OV_INSTPTR_fb_functionblock	pfb,
	OV_TIME						*pltc
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_getVar pinst = Ov_StaticPtrCast(sosx_getVar, pfb);

    return;
}

