
/******************************************************************************
*
*   FILE
*   ----
*   informationModelManagement.c
*
*   History
*   -------
*   2016-08-18   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_createSimpleSoSContainer(
		SOSX_SoSContainerDescription		*SoSContainerSpec,
		OV_INSTPTR_sosx_SoSContainer 		*ppCreatedSoSContainer
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_SimpleSoSContainerUpdate(
		SOSX_SoSContainerDescription	*SoSContainerSpec
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_readSoSContainer(
		OV_INSTPTR_sosx_SoSContainer		pSoSContainerToBeRead,
		OV_INSTPTR_ov_domain				pTragetContainer,
		OV_BOOL								readStateOnly
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_createSimpleSystem(
		SOSX_SystemDescription				*SystemSpec,
		OV_INSTPTR_sosx_System 				*ppCreatedSystem
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_SimpleSystemUpdate(
		SOSX_SystemDescription	*SystemSpec
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_readSystem(
		OV_INSTPTR_sosx_System				pSystemToBeRead,
		OV_INSTPTR_ov_domain				pTargetContainer,
		OV_BOOL								readStateOnly
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_createSimpleProcess(
		SOSX_ProcessDescription				*ProcessSpec,
		OV_INSTPTR_sosx_Process 			*ppCreatedProcess
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_SimpleProcessUpdate(
		SOSX_ProcessDescription	*ProcessSpec
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_readProcess(
		OV_INSTPTR_sosx_Process				pProcessToBeRead,
		OV_INSTPTR_ov_domain				pTargetContainer,
		OV_BOOL								readStateOnly
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_createSimplePort(
		SOSX_PortDescription				*PortSpec,
		OV_INSTPTR_sosx_Port				*ppCreatedPort
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_SimplePortUpdate(
		SOSX_PortDescription	*PortSpec
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_readPort(
		OV_INSTPTR_sosx_Port				pPortToBeRead,
		OV_INSTPTR_ov_domain				pTragetContainer,
		OV_BOOL								readStateOnly
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_createSimpleSourceSink(
		SOSX_SourceSinkDescription			*SourceSinkSpec,
		OV_INSTPTR_sosx_SourceSink			*ppCreatedSourceSink
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_SimpleSourceSinkUpdate(
		SOSX_SourceSinkDescription	*SourceSinkSpec
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_readSourceSink(
		OV_INSTPTR_sosx_SourceSink			pSourceSinkToBeRead,
		OV_INSTPTR_ov_domain				pTragetContainer,
		OV_BOOL								readStateOnly
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_createSimpleDistributionNode(
		SOSX_DistributionNodeDescription	*DistributionNodeSpec,
		OV_INSTPTR_sosx_DistributionNode	*ppCreatedDistributionNode
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_SimpleDistributionNodeUpdate(
		SOSX_DistributionNodeDescription	*DistributionNodeSpec
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_readDistributionNode(
		OV_INSTPTR_sosx_DistributionNode	pDistributionNodeToBeRead,
		OV_INSTPTR_ov_domain				pTragetContainer,
		OV_BOOL								readStateOnly
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_createSimpleProperty(
		SOSX_PropertyDescription			*PropertySpec,
		OV_INSTPTR_sosx_Property			*ppCreatedProperty
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_SimplePropertyUpdate(
		SOSX_PropertyDescription	*PropertySpec
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_readProperty(
		OV_INSTPTR_sosx_Property			pPropertyToBeRead,
		OV_INSTPTR_ov_domain				pTragetContainer,
		OV_BOOL								readStateOnly
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_createSimplePropertyInformation(
		SOSX_PropertyInformationDescription	*PropertyInformationSpec,
		OV_INSTPTR_sosx_PropertyInformation	*ppCreatedPropertyInformation
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_SimplePropertyInformationUpdate(
		SOSX_PropertyInformationDescription	*PropertyInformationUpdateSpec
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_readPropertyInformation(
		OV_INSTPTR_sosx_PropertyInformation			pPropertyInformationToBeRead,
		OV_INSTPTR_ov_domain						pTragetContainer,
		OV_BOOL										readStateOnly
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_createSimpleStream(
		SOSX_StreamDescription				*StreamSpec,
		OV_INSTPTR_sosx_Stream				*ppCreatedStream
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_SimpleStreamUpdate(
		SOSX_StreamDescription	*StreamSpec
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_readStream(
		OV_INSTPTR_sosx_Stream				pStreamToBeRead,
		OV_INSTPTR_ov_domain				pTragetContainer,
		OV_BOOL								readStateOnly
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_createAlternative(
		OV_INSTPTR_sosx_System				pTargetElement,
		OV_INSTPTR_caex_InternalElement		pInternalElement
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_informationModelManagement_readAlternative(
		OV_INSTPTR_sosx_Alternative			pAlternativeToBeRead,
		OV_INSTPTR_ov_domain				pTragetContainer,
		OV_BOOL								readStateOnly
) {

    return OV_ERR_OK;
}

