
/******************************************************************************
*
*   FILE
*   ----
*   isLinkedToSideB.c
*
*   History
*   -------
*   2016-08-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_association.h"

#include "libov/ov_macros.h"

OV_IMPL_LINK(sosx_isLinkedToSideB)
OV_IMPL_UNLINK(sosx_isLinkedToSideB)
OV_IMPL_GETACCESS(sosx_isLinkedToSideB)

