
/******************************************************************************
*
*   FILE
*   ----
*   PropertyInformation.c
*
*   History
*   -------
*   2016-08-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_STRING sosx_PropertyInformation_type_get(
    OV_INSTPTR_sosx_PropertyInformation          pobj
) {
    return pobj->v_type;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_type_set(
    OV_INSTPTR_sosx_PropertyInformation          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_type,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_PropertyInformation_source_get(
    OV_INSTPTR_sosx_PropertyInformation          pobj
) {
    return pobj->v_source;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_source_set(
    OV_INSTPTR_sosx_PropertyInformation          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_source,value);
}

OV_DLLFNCEXPORT OV_INT sosx_PropertyInformation_datatype_get(
    OV_INSTPTR_sosx_PropertyInformation          pobj
) {
    return pobj->v_datatype;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_datatype_set(
    OV_INSTPTR_sosx_PropertyInformation          pobj,
    const OV_INT  value
) {
    pobj->v_datatype = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_ANY* sosx_PropertyInformation_value_get(
    OV_INSTPTR_sosx_PropertyInformation          pobj
) {
    return &pobj->v_value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_value_set(
    OV_INSTPTR_sosx_PropertyInformation          pobj,
    const OV_ANY*  value
) {
    return ov_variable_setanyvalue(&pobj->v_value, value);
}

OV_DLLFNCEXPORT OV_ANY* sosx_PropertyInformation_valueVec_get(
    OV_INSTPTR_sosx_PropertyInformation          pobj
) {
    return &pobj->v_valueVec;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_valueVec_set(
    OV_INSTPTR_sosx_PropertyInformation          pobj,
    const OV_ANY*  value
) {
    return ov_variable_setanyvalue(&pobj->v_valueVec, value);
}

OV_DLLFNCEXPORT OV_UINT sosx_PropertyInformation_index_get(
    OV_INSTPTR_sosx_PropertyInformation          pobj
) {
    return pobj->v_index;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_index_set(
    OV_INSTPTR_sosx_PropertyInformation          pobj,
    const OV_UINT  value
) {
    pobj->v_index = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_TIME* sosx_PropertyInformation_timeStamps_get(
    OV_INSTPTR_sosx_PropertyInformation          pobj,
    OV_UINT *pveclen
) {
    *pveclen = pobj->v_timeStamps.veclen;
    return pobj->v_timeStamps.value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_timeStamps_set(
    OV_INSTPTR_sosx_PropertyInformation          pobj,
    const OV_TIME*  value,
    const OV_UINT veclen
) {
    return Ov_SetDynamicVectorValue(&pobj->v_timeStamps,value,veclen,TIME);
}

OV_DLLFNCEXPORT OV_STRING sosx_PropertyInformation_unit_get(
    OV_INSTPTR_sosx_PropertyInformation          pobj
) {
    return pobj->v_unit;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_unit_set(
    OV_INSTPTR_sosx_PropertyInformation          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_unit,value);
}

OV_DLLFNCEXPORT OV_UINT sosx_PropertyInformation_memsize_get(
    OV_INSTPTR_sosx_PropertyInformation          pobj
) {
    return pobj->v_memsize;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_memsize_set(
    OV_INSTPTR_sosx_PropertyInformation          pobj,
    const OV_UINT  value
) {
    pobj->v_memsize = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_PropertyInformation pinst = Ov_StaticPtrCast(sosx_PropertyInformation, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_addValueToVec(
		OV_INSTPTR_sosx_PropertyInformation			pobj,
		const OV_ANY								*pValue
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_addTimeStamp(
		OV_INSTPTR_sosx_PropertyInformation			pobj,
		const OV_TIME								*Time
) {

    return OV_ERR_OK;
}

