
/******************************************************************************
*
*   FILE
*   ----
*   SoSContainer.c
*
*   History
*   -------
*   2016-08-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_STRING sosx_SoSContainer_name_get(
    OV_INSTPTR_sosx_SoSContainer          pobj
) {
    return pobj->v_name;
}

OV_DLLFNCEXPORT OV_RESULT sosx_SoSContainer_name_set(
    OV_INSTPTR_sosx_SoSContainer          pobj,
    const OV_STRING  value
) {
    return ov_string_setvalue(&pobj->v_name,value);
}

OV_DLLFNCEXPORT OV_STRING* sosx_SoSContainer_externalReference_get(
    OV_INSTPTR_sosx_SoSContainer          pobj,
    OV_UINT *pveclen
) {
    *pveclen = pobj->v_externalReference.veclen;
    return pobj->v_externalReference.value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_SoSContainer_externalReference_set(
    OV_INSTPTR_sosx_SoSContainer          pobj,
    const OV_STRING*  value,
    const OV_UINT veclen
) {
    return Ov_SetDynamicVectorValue(&pobj->v_externalReference,value,veclen,STRING);
}

OV_DLLFNCEXPORT OV_RESULT sosx_SoSContainer_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_SoSContainer pinst = Ov_StaticPtrCast(sosx_SoSContainer, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

