
/******************************************************************************
*
*   FILE
*   ----
*   sosxdomain.c
*
*   History
*   -------
*   2016-08-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_UINT sosx_sosxdomain_readStyle_get(
    OV_INSTPTR_sosx_sosxdomain          pobj
) {
    return pobj->v_readStyle;
}

OV_DLLFNCEXPORT OV_RESULT sosx_sosxdomain_readStyle_set(
    OV_INSTPTR_sosx_sosxdomain          pobj,
    const OV_UINT  value
) {
    pobj->v_readStyle = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_UINT sosx_sosxdomain_isValid_get(
    OV_INSTPTR_sosx_sosxdomain          pobj
) {
    return pobj->v_isValid;
}

OV_DLLFNCEXPORT OV_RESULT sosx_sosxdomain_isValid_set(
    OV_INSTPTR_sosx_sosxdomain          pobj,
    const OV_UINT  value
) {
    pobj->v_isValid = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_STRING sosx_sosxdomain_caexLibrary_get(
    OV_INSTPTR_sosx_sosxdomain          pobj
) {
    return pobj->v_caexLibrary;
}

OV_DLLFNCEXPORT OV_UINT sosx_sosxdomain_xPos_get(
    OV_INSTPTR_sosx_sosxdomain          pobj
) {
    return pobj->v_xPos;
}

OV_DLLFNCEXPORT OV_RESULT sosx_sosxdomain_xPos_set(
    OV_INSTPTR_sosx_sosxdomain          pobj,
    const OV_UINT  value
) {
    pobj->v_xPos = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_UINT sosx_sosxdomain_yPos_get(
    OV_INSTPTR_sosx_sosxdomain          pobj
) {
    return pobj->v_yPos;
}

OV_DLLFNCEXPORT OV_RESULT sosx_sosxdomain_yPos_set(
    OV_INSTPTR_sosx_sosxdomain          pobj,
    const OV_UINT  value
) {
    pobj->v_yPos = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_sosxdomain_restIsValidIfValueChanged(
		OV_INSTPTR_sosx_sosxdomain			pobj
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_sosxdomain_setCaexLibrary(
		OV_INSTPTR_sosx_sosxdomain			pobj,
		OV_INSTPTR_caex_CAEXBasicObject		pIE,
		const OV_STRING  					value
) {

    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_ACCESS sosx_sosxdomain_getaccess(
	OV_INSTPTR_ov_object	pobj,
	const OV_ELEMENT		*pelem,
	const OV_TICKET			*pticket
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_sosxdomain pinst = Ov_StaticPtrCast(sosx_sosxdomain, pobj);

    return (OV_ACCESS)0;
}

OV_DLLFNCEXPORT void sosx_sosxdomain_destructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_sosxdomain pinst = Ov_StaticPtrCast(sosx_sosxdomain, pobj);

    /* do what */

    /* destroy object */
    ov_object_destructor(pobj);

    return;
}

