
/******************************************************************************
*
*   FILE
*   ----
*   StructureElement.c
*
*   History
*   -------
*   2016-08-10   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_STRING* sosx_StructureElement_externalInfo_get(
    OV_INSTPTR_sosx_StructureElement          pobj,
    OV_UINT *pveclen
) {
    *pveclen = pobj->v_externalInfo.veclen;
    return pobj->v_externalInfo.value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StructureElement_externalInfo_set(
    OV_INSTPTR_sosx_StructureElement          pobj,
    const OV_STRING*  value,
    const OV_UINT veclen
) {
    return Ov_SetDynamicVectorValue(&pobj->v_externalInfo,value,veclen,STRING);
}

OV_DLLFNCEXPORT OV_UINT* sosx_StructureElement_externalInfoStat_get(
    OV_INSTPTR_sosx_StructureElement          pobj,
    OV_UINT *pveclen
) {
    *pveclen = pobj->v_externalInfoStat.veclen;
    return pobj->v_externalInfoStat.value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StructureElement_externalInfoStat_set(
    OV_INSTPTR_sosx_StructureElement          pobj,
    const OV_UINT*  value,
    const OV_UINT veclen
) {
    return Ov_SetDynamicVectorValue(&pobj->v_externalInfoStat,value,veclen,UINT);
}

OV_DLLFNCEXPORT OV_BOOL* sosx_StructureElement_resetExtInfoStat_get(
    OV_INSTPTR_sosx_StructureElement          pobj,
    OV_UINT *pveclen
) {
    *pveclen = pobj->v_resetExtInfoStat.veclen;
    return pobj->v_resetExtInfoStat.value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StructureElement_resetExtInfoStat_set(
    OV_INSTPTR_sosx_StructureElement          pobj,
    const OV_BOOL*  value,
    const OV_UINT veclen
) {
    return Ov_SetDynamicVectorValue(&pobj->v_resetExtInfoStat,value,veclen,BOOL);
}

OV_DLLFNCEXPORT OV_INT sosx_StructureElement_width_get(
    OV_INSTPTR_sosx_StructureElement          pobj
) {
    return pobj->v_width;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StructureElement_width_set(
    OV_INSTPTR_sosx_StructureElement          pobj,
    const OV_INT  value
) {
    pobj->v_width = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_INT sosx_StructureElement_height_get(
    OV_INSTPTR_sosx_StructureElement          pobj
) {
    return pobj->v_height;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StructureElement_height_set(
    OV_INSTPTR_sosx_StructureElement          pobj,
    const OV_INT  value
) {
    pobj->v_height = value;
    return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StructureElement_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    OV_INSTPTR_sosx_StructureElement pinst = Ov_StaticPtrCast(sosx_StructureElement, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

