
/******************************************************************************
*
*   FILE
*   ----
*   StreamHandler.c
*
*   History
*   -------
*   2014-11-13   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_UINT sosx_StreamHandler_numProp_get(
    OV_INSTPTR_sosx_StreamHandler          pobj
) {
	OV_INSTPTR_sosx_Property			pProp	= NULL;
	OV_UINT								numProp	= 0;

	Ov_ForEachChildEx(ov_containment, pobj, pProp, sosx_Property){
		numProp = numProp + 1;
	}

	pobj->v_numProp = numProp;

    return pobj->v_numProp;
}

OV_DLLFNCEXPORT OV_STRING sosx_StreamHandler_StreamType_get(
    OV_INSTPTR_sosx_StreamHandler          pobj
) {
    return pobj->v_StreamType;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StreamHandler_StreamType_set(
    OV_INSTPTR_sosx_StreamHandler          pobj,
    const OV_STRING  value
) {
	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

    return ov_string_setvalue(&pobj->v_StreamType,value);
}
OV_DLLFNCEXPORT OV_STRING sosx_StreamHandler_wasConnectedTo_get(
    OV_INSTPTR_sosx_StreamHandler          pobj
) {
    return pobj->v_wasConnectedTo;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StreamHandler_wasConnectedTo_set(
    OV_INSTPTR_sosx_StreamHandler          pobj,
    const OV_STRING  value
) {
	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

    return ov_string_setvalue(&pobj->v_wasConnectedTo,value);
}

OV_DLLFNCEXPORT OV_RESULT sosx_StreamHandler_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
   // OV_INSTPTR_sosx_StreamHandler pinst = Ov_StaticPtrCast(sosx_StreamHandler, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

