
/******************************************************************************
 *
 *   FILE
 *   ----
 *   StructureElement.c
 *
 *   History
 *   -------
 *   2016-05-09   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"
#include "sosxcommon.h"

OV_DLLFNCEXPORT OV_STRING* sosx_StructureElement_externalInfo_get(
		OV_INSTPTR_sosx_StructureElement          pobj,
		OV_UINT *pveclen
) {
	*pveclen = pobj->v_externalInfo.veclen;
	return pobj->v_externalInfo.value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StructureElement_externalInfo_set(
		OV_INSTPTR_sosx_StructureElement          pobj,
		const OV_STRING*  value,
		const OV_UINT veclen
) {
	OV_INSTPTR_sosx_FileMonitor					pMonitor				= NULL;
	OV_RESULT									result					= OV_ERR_OK;
	OV_UINT_VEC									externalInfoStatTemp	= {0,NULL};
	OV_BOOL_VEC									resetExtInfoStatTemp	= {0,NULL};
	OV_BOOL										found					= FALSE;

	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

	// do nothing if value is (null)
	if(veclen == 0 ||
			(veclen == 1 &&
			(ov_string_compare(value[0],"(null)") == OV_STRCMP_EQUAL))){
		return result;
	}

	if(ov_string_compare(value[0],"-") == OV_STRCMP_EQUAL){
		Ov_SetDynamicVectorValue(&pobj->v_externalInfo,value,veclen,STRING);
		return result;
	}
	// match vector length of externalInfo, Status and Reset vector
	Ov_SetDynamicVectorLength(&externalInfoStatTemp,veclen,UINT);
	Ov_SetDynamicVectorLength(&resetExtInfoStatTemp,veclen,BOOL);

	// compare current and new externalInfo
	for(OV_UINT i = 0; i<veclen ;i++){
		for(OV_UINT j = 0; j<pobj->v_externalInfo.veclen ;j++){
			if(ov_string_compare(value[i],pobj->v_externalInfo.value[j]) == OV_STRCMP_EQUAL){
				// match the other two vectors if user change the order
				found = TRUE;
				externalInfoStatTemp.value[i] = pobj->v_externalInfoStat.value[j];
				resetExtInfoStatTemp.value[i] = pobj->v_resetExtInfoStat.value[j];
			} else {
				found = FALSE;
			}
		}
		if(!found){
			// set other two vectors to default value if user added new externalInfo
			externalInfoStatTemp.value[i] = SOSX_EXTERNALINFOSTATE_NOTCHECKED;
			resetExtInfoStatTemp.value[i] = FALSE;
		}
	}

	// monitor externalInfo for changes and inform user if file has changed/ can not be found etc
	//nothing to do if veclen is 0
	if(veclen == 0){
		return result;
	}

	// check if FileMonitor fb already exists; create FileMonitor fb if it does not exist
	if(NULL != Ov_SearchChildEx(ov_containment,pobj,"FileMonitor",sosx_FileMonitor)){
		pMonitor = Ov_SearchChildEx(ov_containment,pobj,"FileMonitor",sosx_FileMonitor);
	}else{
		// does not exist -> create
		result = Ov_CreateObject(sosx_FileMonitor,pMonitor,pobj,"FileMonitor");
		if(Ov_Fail(result)){
			return result;
		}
	}

	// configure fb
	// stop cyclic execution of fb
	pMonitor->v_iexreq = FALSE;

	// set and push externalInfo
	Ov_SetDynamicVectorValue(&pobj->v_externalInfo,value,veclen,STRING);
	result = sosx_FileMonitor_filePath_set(pMonitor,pobj->v_externalInfo.value,pobj->v_externalInfo.veclen);
	if(Ov_Fail(result)){
		return result;
	}

	// set the other two vectors
	sosx_StructureElement_externalInfoStat_set(pobj,externalInfoStatTemp.value,veclen);
	sosx_StructureElement_resetExtInfoStat_set(pobj,resetExtInfoStatTemp.value,veclen);

	// restart cyclic execution
	pMonitor->v_iexreq = TRUE;

	return result;
}

OV_DLLFNCEXPORT OV_UINT* sosx_StructureElement_externalInfoStat_get(
		OV_INSTPTR_sosx_StructureElement          pobj,
		OV_UINT *pveclen
) {
	*pveclen = pobj->v_externalInfoStat.veclen;
	return pobj->v_externalInfoStat.value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StructureElement_externalInfoStat_set(
		OV_INSTPTR_sosx_StructureElement          pobj,
		const OV_UINT*  value,
		const OV_UINT veclen
) {
	return Ov_SetDynamicVectorValue(&pobj->v_externalInfoStat,value,veclen,UINT);
}

OV_DLLFNCEXPORT OV_BOOL* sosx_StructureElement_resetExtInfoStat_get(
		OV_INSTPTR_sosx_StructureElement          pobj,
		OV_UINT *pveclen
) {
	*pveclen = pobj->v_resetExtInfoStat.veclen;
	return pobj->v_resetExtInfoStat.value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StructureElement_resetExtInfoStat_set(
		OV_INSTPTR_sosx_StructureElement          pobj,
		const OV_BOOL*  value,
		const OV_UINT veclen
) {
	OV_INSTPTR_sosx_FileMonitor		pMonitor	= NULL;

	// try to find the FileMonitor fb
	if(NULL != Ov_SearchChildEx(ov_containment,pobj,"FileMonitor",sosx_FileMonitor)){
		pMonitor = Ov_SearchChildEx(ov_containment,pobj,"FileMonitor",sosx_FileMonitor);
		sosx_FileMonitor_reset_set(pMonitor,value,veclen);
	}

	return Ov_SetDynamicVectorValue(&pobj->v_resetExtInfoStat,value,veclen,BOOL);
}

OV_DLLFNCEXPORT OV_INT sosx_StructureElement_height_get(
		OV_INSTPTR_sosx_StructureElement          pobj
) {
	OV_INSTPTR_sosx_Port			pPort		= NULL;
	OV_INSTPTR_sosx_Property		pProperty	= NULL;
	OV_UINT							numInPort	= 0;
	OV_UINT							numOutPort	= 0;
	OV_UINT							numProp		= 0;
	OV_UINT							pixPerEle	= 1;
	OV_UINT							minHight	= 0;
	OV_UINT							offset		= 0;


	/*Count Ports */
	Ov_ForEachChildEx(ov_containment ,pobj, pPort, sosx_Port)
	{
		if(sosx_Port_portType_get(pPort) == 0)
		{
			numOutPort = numOutPort + 1;
		}
		else if (sosx_Port_portType_get(pPort) == 1)
		{
			numInPort = numInPort + 1;
		}
	}
	/*Count Properties*/

	Ov_ForEachChildEx(ov_containment ,pobj, pProperty, sosx_Property)
	{
		numProp = numProp + 1;
	}

	pobj->v_height = max_uint(pixPerEle * max_uint(numProp,max_uint(numInPort,numOutPort)) + offset ,minHight);

	return pobj->v_height;
}

OV_DLLFNCEXPORT OV_INT sosx_StructureElement_width_get(
		OV_INSTPTR_sosx_StructureElement          pobj
) {
	OV_INSTPTR_sosx_Port			pPort		= NULL;
	OV_UINT							numUnPort	= 0;
	OV_UINT							pixPerEle	= 1;
	OV_UINT							minWidth	= 0;
	OV_UINT							offset		= 0;


	/*Count Ports */
	Ov_ForEachChildEx(ov_containment ,pobj, pPort, sosx_Port)
	{
		if(sosx_Port_portType_get(pPort) == 2)
		{
			numUnPort = numUnPort + 1;
		}
	}
	/*Count Properties*/

	pobj->v_width = max_uint(pixPerEle * numUnPort + offset, minWidth);

	return pobj->v_width;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StructureElement_width_set(
		OV_INSTPTR_sosx_StructureElement          pobj,
		const OV_INT  value
) {
	pobj->v_width = value;
	return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StructureElement_height_set(
		OV_INSTPTR_sosx_StructureElement          pobj,
		const OV_INT  value
) {
	pobj->v_height = value;
	return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_StructureElement_constructor(
		OV_INSTPTR_ov_object 	pobj
) {
	/*
	 *   local variables
	 */
	// OV_INSTPTR_sosx_StructureElement pinst = Ov_StaticPtrCast(sosx_StructureElement, pobj);
	OV_RESULT    result;

	/* do what the base class does first */
	result = ov_object_constructor(pobj);
	if(Ov_Fail(result))
		return result;

	/* do what */


	return OV_ERR_OK;
}

