
/******************************************************************************
 *
 *   FILE
 *   ----
 *   BaseElement.c
 *
 *   History
 *   -------
 *   2014-11-28   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"



OV_DLLFNCEXPORT OV_TIME* sosx_BaseElement_validFrom_get(
		OV_INSTPTR_sosx_BaseElement          pobj
) {
	return &pobj->v_validFrom;
}

OV_DLLFNCEXPORT OV_RESULT sosx_BaseElement_validFrom_set(
		OV_INSTPTR_sosx_BaseElement          pobj,
		const OV_TIME*  value
) {
	OV_RESULT			result			= OV_ERR_OK;
	OV_TIME				null			= {0,0};
	OV_TIME				internalValue	= {0,0};

	result = sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));
	if(Ov_Fail(result)){
		return OV_ERR_GENERIC;
	}

	internalValue = *value;

	if(ov_time_compare(value,&null) == OV_TIMECMP_EQUAL && Ov_CanCastTo(sosx_BaseElement,Ov_GetParent(ov_containment,Ov_GetParent(ov_containment,pobj)))){
		if(Ov_CanCastTo(sosx_PropertyInformation,pobj)){
			internalValue = *sosx_BaseElement_validFrom_get(Ov_DynamicPtrCast(sosx_BaseElement,Ov_GetParent(ov_containment,Ov_GetParent(ov_containment,pobj))));
		}
		if(Ov_CanCastTo(sosx_DetailedElement,pobj) && Ov_CanCastTo(sosx_BaseElement,Ov_GetParent(ov_containment,pobj))){
			internalValue = *sosx_BaseElement_validFrom_get(Ov_DynamicPtrCast(sosx_BaseElement,Ov_GetParent(ov_containment,pobj)));
		}
	}

	pobj->v_validFrom = internalValue;
	return result;
}

OV_DLLFNCEXPORT OV_TIME* sosx_BaseElement_validUntil_get(
		OV_INSTPTR_sosx_BaseElement          pobj
) {
	return &pobj->v_validUntil;
}

OV_DLLFNCEXPORT OV_RESULT sosx_BaseElement_validUntil_set(
		OV_INSTPTR_sosx_BaseElement          pobj,
		const OV_TIME*  value
) {
	OV_RESULT						result			= OV_ERR_OK;
	OV_TIME							null			= {0,0};
	OV_TIME							internalValue	= {0,0};
	OV_INSTPTR_sosx_BaseElement		pParent 		= NULL;

	result = sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));
	if(Ov_Fail(result)){
		return OV_ERR_GENERIC;
	}

	internalValue = *value;

	if(ov_time_compare(value,&null) == OV_TIMECMP_EQUAL && Ov_CanCastTo(sosx_BaseElement,Ov_GetParent(ov_containment,Ov_GetParent(ov_containment,pobj)))){
		if(Ov_CanCastTo(sosx_PropertyInformation,pobj)){
			pParent = Ov_DynamicPtrCast(sosx_BaseElement,Ov_GetParent(ov_containment,Ov_GetParent(ov_containment,pobj)));
			internalValue = *sosx_BaseElement_validUntil_get(pParent);
		}
		if(Ov_CanCastTo(sosx_DetailedElement,pobj) && Ov_CanCastTo(sosx_BaseElement,Ov_GetParent(ov_containment,pobj))){
			pParent = Ov_DynamicPtrCast(sosx_BaseElement,Ov_GetParent(ov_containment,pobj));
			internalValue = *sosx_BaseElement_validUntil_get(pParent);
		}
	}

	pobj->v_validUntil = internalValue;
	return result;
}

OV_DLLFNCEXPORT OV_ACCESS sosx_BaseElement_getaccess(
		OV_INSTPTR_ov_object	pobj,
		const OV_ELEMENT		*pelem,
		const OV_TICKET			*pticket
) {
	/*
	 *   local variables
	 */
	// OV_INSTPTR_sosx_BaseElement pinst = Ov_StaticPtrCast(sosx_BaseElement, pobj);

	return ov_object_getaccess(pobj, pelem, pticket);
}

OV_DLLFNCEXPORT void sosx_BaseElement_destructor(
		OV_INSTPTR_ov_object 	pobj
) {
	/*
	 *   local variables
	 */
	// OV_INSTPTR_sosx_BaseElement pinst = Ov_StaticPtrCast(sosx_BaseElement, pobj);

	/* do what */

	/* destroy object */
	ov_object_destructor(pobj);

	return;
}

