
/******************************************************************************
 *
 *   FILE
 *   ----
 *   PropertyInformation.c
 *
 *   History
 *   -------
 *   2015-05-06   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "sosxcommon.h"
#include "libov/ov_macros.h"
#include "fbcomlib.h"
#include "string.h"


OV_DLLFNCEXPORT OV_UINT sosx_Property_numPropInfo_get(
		OV_INSTPTR_sosx_Property          pobj
) {
	OV_INSTPTR_sosx_PropertyInformation	pPropInfo	= NULL;
	OV_UINT								numPropInfo	= 0;

	Ov_ForEachChildEx(ov_containment, pobj, pPropInfo, sosx_PropertyInformation){
		numPropInfo = numPropInfo + 1;
	}

	pobj->v_numPropInfo = numPropInfo;

	return pobj->v_numPropInfo;
}

OV_DLLFNCEXPORT OV_STRING sosx_PropertyInformation_type_get(
		OV_INSTPTR_sosx_PropertyInformation          pobj
) {
	return pobj->v_type;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_type_set(
		OV_INSTPTR_sosx_PropertyInformation          pobj,
		const OV_STRING  value
) {
	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));
	return ov_string_setvalue(&pobj->v_type,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_PropertyInformation_source_get(
		OV_INSTPTR_sosx_PropertyInformation          pobj
) {
	return pobj->v_source;
}

OV_DLLFNCEXPORT OV_UINT sosx_PropertyInformation_index_get(
		OV_INSTPTR_sosx_PropertyInformation          pobj
) {
	return pobj->v_index;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_index_set(
		OV_INSTPTR_sosx_PropertyInformation          pobj,
		const OV_UINT  value
) {
	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

	pobj->v_index = value;
	return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_INT sosx_PropertyInformation_datatype_get(
		OV_INSTPTR_sosx_PropertyInformation          pobj
) {
	return pobj->v_datatype;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_datatype_set(
		OV_INSTPTR_sosx_PropertyInformation          pobj,
		const OV_INT  value
) {
	OV_RESULT 		result = OV_ERR_OK;

	switch (value & OV_VT_KSMASK){

	case (OV_VT_STRING) : {
		pobj->v_valueVec.value.vartype = OV_VT_STRING_VEC;
		pobj->v_value.value.vartype = OV_VT_STRING;
		break;
	}
	case (OV_VT_BOOL) : {
		pobj->v_valueVec.value.vartype = OV_VT_BOOL_VEC;
		pobj->v_value.value.vartype = OV_VT_BOOL;
		break;
	}
	case  (OV_VT_INT) : {
		pobj->v_valueVec.value.vartype = OV_VT_INT_VEC;
		pobj->v_value.value.vartype = OV_VT_INT;
		break;
	}
	case (OV_VT_UINT) : {
		pobj->v_valueVec.value.vartype = OV_VT_UINT_VEC;
		pobj->v_value.value.vartype = OV_VT_UINT;
		break;
	}
	case (OV_VT_SINGLE) : {
		pobj->v_valueVec.value.vartype = OV_VT_SINGLE_VEC;
		pobj->v_value.value.vartype = OV_VT_SINGLE;
		break;
	}
	case (OV_VT_DOUBLE) : {
		pobj->v_valueVec.value.vartype = OV_VT_DOUBLE_VEC;
		pobj->v_value.value.vartype = OV_VT_DOUBLE;
		break;
	}
	default :
		logfile_error("unknown datatype",pobj->v_identifier);
		return OV_ERR_BADTYPE;
	}
	pobj->v_datatype = value;
	return result;
}

OV_DLLFNCEXPORT OV_UINT sosx_PropertyInformation_memsize_get(
		OV_INSTPTR_sosx_PropertyInformation          pobj
) {
	return pobj->v_memsize;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_memsize_set(
		OV_INSTPTR_sosx_PropertyInformation          pobj,
		const OV_UINT  value
) {

	OV_RESULT						result 		= OV_ERR_OK;

	OV_TIME_VEC						TimeBuf		= {0,NULL};
	OV_ANY							ValBuf		= {};

# undef Finally
#define Finally()					\
		Ov_SetAnyValue(&ValBuf,NULL);	\

	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

	/* memory size has been increased, set vector length */
	if(value > pobj->v_memsize){
		Ov_SetDynamicVectorLength(&pobj->v_timeStamps,value,TIME);

		switch (pobj->v_datatype & OV_VT_KSMASK){

		case (OV_VT_STRING) : {
			Ov_SetDynamicVectorLength(&pobj->v_valueVec.value.valueunion.val_string_vec,value,STRING);
			break;
		}
		case (OV_VT_BOOL) : {
			Ov_SetDynamicVectorLength(&pobj->v_valueVec.value.valueunion.val_bool_vec,value,BOOL);
			break;
		}
		case  (OV_VT_INT) : {
			Ov_SetDynamicVectorLength(&pobj->v_valueVec.value.valueunion.val_int_vec,value,INT);
			break;
		}
		case (OV_VT_UINT) : {
			Ov_SetDynamicVectorLength(&pobj->v_valueVec.value.valueunion.val_uint_vec,value,UINT);
			break;
		}
		case (OV_VT_SINGLE) : {
			Ov_SetDynamicVectorLength(&pobj->v_valueVec.value.valueunion.val_single_vec,value,SINGLE);
			break;
		}
		case (OV_VT_DOUBLE) : {
			Ov_SetDynamicVectorLength(&pobj->v_valueVec.value.valueunion.val_double_vec,value,DOUBLE);
			break;
		}
		}
	}

	/* memory size has been reduced. Move values and reduce the memory size */
	if(value < pobj->v_memsize && value > 1){

		Ov_SetAnyValue(&ValBuf,&pobj->v_valueVec);
		result = Ov_SetDynamicVectorValue(&TimeBuf,&pobj->v_timeStamps.value,pobj->v_timeStamps.veclen,TIME);

		switch(pobj->v_datatype & OV_VT_KSMASK){

		case (OV_VT_STRING) : {
			Ov_SetDynamicVectorLength(&pobj->v_valueVec.value.valueunion.val_string_vec,value,STRING);
			Ov_SetDynamicVectorLength(&pobj->v_timeStamps,value,TIME);
			for(OV_UINT i = 1;i < value ;i++){
				pobj->v_valueVec.value.valueunion.val_string_vec.value[i] = ValBuf.value.valueunion.val_string_vec.value[pobj->v_index - value + i];
				pobj->v_timeStamps.value[i] = TimeBuf.value[pobj->v_index - value + i];
			}
		}

		break;

		case (OV_VT_BOOL) : {
			Ov_SetDynamicVectorLength(&pobj->v_valueVec.value.valueunion.val_bool_vec,value,BOOL);
			Ov_SetDynamicVectorLength(&pobj->v_timeStamps,value,TIME);
			for(OV_UINT i = 1;i < value ;i++){
				pobj->v_valueVec.value.valueunion.val_bool_vec.value[i] = ValBuf.value.valueunion.val_bool_vec.value[pobj->v_index - value + i];
				pobj->v_timeStamps.value[i] = TimeBuf.value[pobj->v_index - value + i];
			}
		}

		break;

		case  (OV_VT_INT) : {
			Ov_SetDynamicVectorLength(&pobj->v_valueVec.value.valueunion.val_int_vec,value,INT);
			Ov_SetDynamicVectorLength(&pobj->v_timeStamps,value,TIME);
			for(OV_UINT i = 1;i < value ;i++){
				pobj->v_valueVec.value.valueunion.val_int_vec.value[i] = ValBuf.value.valueunion.val_int_vec.value[pobj->v_index - value + i];
				pobj->v_timeStamps.value[i] = TimeBuf.value[pobj->v_index - value + i];
			}
		}
		break;

		case (OV_VT_UINT) : {
			Ov_SetDynamicVectorLength(&pobj->v_valueVec.value.valueunion.val_uint_vec,value,UINT);
			Ov_SetDynamicVectorLength(&pobj->v_timeStamps,value,TIME);
			for(OV_UINT i = 1;i < value ;i++){
				pobj->v_valueVec.value.valueunion.val_uint_vec.value[i] = ValBuf.value.valueunion.val_uint_vec.value[pobj->v_index - value + i];
				pobj->v_timeStamps.value[i] = TimeBuf.value[pobj->v_index - value + i];
			}
		}
		break;

		case (OV_VT_SINGLE) : {
			Ov_SetDynamicVectorLength(&pobj->v_valueVec.value.valueunion.val_single_vec,value,SINGLE);
			Ov_SetDynamicVectorLength(&pobj->v_timeStamps,value,TIME);
			for(OV_UINT i = 1;i < value ;i++){
				pobj->v_valueVec.value.valueunion.val_single_vec.value[i] = ValBuf.value.valueunion.val_single_vec.value[pobj->v_index - value + i];
				pobj->v_timeStamps.value[i] = TimeBuf.value[pobj->v_index - value + i];
			}
		}
		break;

		case (OV_VT_DOUBLE) : {
			Ov_SetDynamicVectorLength(&pobj->v_valueVec.value.valueunion.val_double_vec,value,DOUBLE);
			Ov_SetDynamicVectorLength(&pobj->v_timeStamps,value,TIME);
			for(OV_UINT i = 1;i < value ;i++){
				pobj->v_valueVec.value.valueunion.val_double_vec.value[i] = ValBuf.value.valueunion.val_double_vec.value[pobj->v_index - value + i];
				pobj->v_timeStamps.value[i] = TimeBuf.value[pobj->v_index - value + i];
			}
		}
		break;

		default :
			logfile_error("unknown datatype",pobj->v_identifier);
			Finally();
			return OV_ERR_BADTYPE;
		}

		pobj->v_index = 0;
	}

	pobj->v_memsize = value;

	Finally();
	return result;
}

OV_DLLFNCEXPORT OV_TIME* sosx_PropertyInformation_timeStamps_get(
		OV_INSTPTR_sosx_PropertyInformation          pobj,
		OV_UINT *pveclen
) {
	*pveclen = pobj->v_timeStamps.veclen;
	return pobj->v_timeStamps.value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_timeStamps_set(
		OV_INSTPTR_sosx_PropertyInformation          pobj,
		const OV_TIME*  value,
		const OV_UINT veclen
) {
	OV_RESULT		result = OV_ERR_OK;

	result = Ov_SetDynamicVectorValue(&pobj->v_timeStamps,value,veclen,TIME);
	Ov_SetDynamicVectorLength(&pobj->v_timeStamps,pobj->v_memsize,TIME);

	return result;
}

OV_DLLFNCEXPORT OV_ANY* sosx_PropertyInformation_valueVec_get(
		OV_INSTPTR_sosx_PropertyInformation          pobj
) {
	return &pobj->v_valueVec;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_valueVec_set(
		OV_INSTPTR_sosx_PropertyInformation          pobj,
		const OV_ANY*  value
) {
	return ov_variable_setanyvalue(&pobj->v_valueVec, value);

}

OV_RESULT sosx_PropertyInformation_source_parse(
		OV_STRING		*value,
		OV_STRING		*schema,
		OV_STRING		*host,
		OV_STRING		*server,
		OV_STRING		*path,
		OV_TIME_SPAN	*cycletime,
		OV_UINT			*memsize
){
	OV_STRING			tmpStr			= NULL;
	OV_STRING			tmpStr2			= NULL;
	OV_STRING			memsizeStr		= NULL;
	OV_STRING			cycletimeStr	= NULL;
	OV_RESULT		 	result			= OV_ERR_OK;

#undef Finally
#define Finally()								\
		ov_string_setvalue(&tmpStr,NULL);		\
		ov_string_setvalue(&tmpStr2,NULL);		\
		ov_string_setvalue(&memsizeStr,NULL);	\
		ov_string_setvalue(&cycletimeStr,NULL);	\


	/* get schema, server, host path cycletime form value
	 * URI:   schema://server/host/path?query (ks://127.0.0.1/MANAGER/TechUnits/add.OUT?cyctime=5&memsize=1)
	 */
	if(!ov_string_match(*value,"*://*/*/*?*=*&*=*"))
	{
		Finally();
		return OV_ERR_OK;
	}

	result = ov_string_setvalue(&tmpStr,*value);
	if(Ov_Fail(result)){
		Finally();
		return result;
	}

	/* schema */
	result = ov_string_setvalue(schema,strtok(tmpStr,":"));
	if(Ov_Fail(result)){
		Finally();
		return result;
	}

	/* host  */
	result = ov_string_setvalue(host,strtok(NULL,"/"));
	if(Ov_Fail(result)){
		Finally();
		return result;
	}

	/* server */
	result = ov_string_setvalue(server,strtok(NULL,"/"));
	if(Ov_Fail(result)){
		Finally();
		return result;
	}

	/* path */
	result = ov_string_setvalue(path,"/");
	if(Ov_Fail(result)){
		Finally();
		return result;
	}
	result = ov_string_append(path,strtok(NULL,"?"));
	if(Ov_Fail(result)){
		Finally();
		return result;
	}

	/* cycletime & memsize*/
	result = ov_string_setvalue(&tmpStr2,strtok(NULL,"&"));
	if(Ov_Fail(result)){
		Finally();
		return result;
	}

	if(ov_string_match(tmpStr2,"cyctime=*")){
		strtok(NULL,"=");
		result = ov_string_setvalue(&memsizeStr,strtok(NULL,"&"));
		if(Ov_Fail(result)){
			Finally();
			return result;
		}
		strtok(tmpStr2,"=");
		result = ov_string_setvalue(&cycletimeStr,strtok(NULL,"&"));
		if(Ov_Fail(result)){
			Finally();
			return result;
		}
	}else{
		strtok(NULL,"=");
		result = ov_string_setvalue(&cycletimeStr,strtok(NULL,"&"));
		if(Ov_Fail(result)){
			Finally();
			return result;
		}
		strtok(tmpStr2,"=");
		result = ov_string_setvalue(&memsizeStr,strtok(NULL,"&"));
		if(Ov_Fail(result)){
			Finally();
			return result;
		}
	}

	cycletime->secs = atoi(cycletimeStr);
	*memsize = atoi(memsizeStr);

	Finally();
	return result;
}

OV_RESULT sosx_PropertyInformation_source_Cofig_getVar(
		OV_INSTPTR_sosx_PropertyInformation         pobj,
		OV_STRING									value

){
	OV_STRING					host		= NULL;
	OV_STRING					schema		= NULL;
	OV_STRING					server		= NULL;
	OV_STRING					path		= NULL;
	OV_TIME_SPAN				cycletime	= {0,0};
	OV_UINT						memsize		= 0;
	OV_RESULT		 			result 		= OV_ERR_OK;
	OV_INSTPTR_sosx_getVar		pGetVar		= NULL;

#undef Finally
#define Finally()								\
		ov_string_setvalue(&host,NULL);			\
		ov_string_setvalue(&server,NULL);		\
		ov_string_setvalue(&path,NULL);			\
		ov_string_setvalue(&schema,NULL);		\

	result =  sosx_PropertyInformation_source_parse(&value, &schema, &host, &server, &path, &cycletime, &memsize);
	if(Ov_Fail(result)){
		Finally();
		return result;
	}

	/* create sosx_getVar fb or update existing getVar fb if source changes */
	pGetVar = Ov_SearchChildEx(ov_containment,pobj,"getVar",sosx_getVar);
	if(pGetVar == NULL){
		result = Ov_CreateObject(sosx_getVar,pGetVar,pobj,"getVar");
		if(Ov_Fail(result)){
			logfile_error("Could not find or create the getVar fb ",pobj->v_identifier);
			Finally();
			return result;
		}
	}

	/* configure getVar */
	/* set memsize */
	result = sosx_PropertyInformation_memsize_set(pobj,memsize);
	if(Ov_Fail(result)){
		logfile_error("Could not set the memsize",pobj->v_identifier);
		Finally();
		return result;
	}

	/* actimode */
	result = fb_task_actimode_set(Ov_DynamicPtrCast(fb_task,pGetVar),0);
	if(Ov_Fail(result)){
		logfile_error("Could not activate the getVar task ",pobj->v_identifier);
		Finally();
		return result;
	}

	/* host */
	result = sosx_getKsVal_host_set(Ov_DynamicPtrCast(sosx_getKsVal,pGetVar),host);
	if(Ov_Fail(result)){
		logfile_error("Could not set the getVar fb host ",pobj->v_identifier);
		Finally();
		return result;
	}

	/* server */
	result = sosx_getKsVal_server_set(Ov_DynamicPtrCast(sosx_getKsVal,pGetVar),server);
	if(Ov_Fail(result)){
		logfile_error("Could not set the getVar fb server ",pobj->v_identifier);
		Finally();
		return result;
	}

	/* path */
	result = sosx_getKsVal_path_set(Ov_DynamicPtrCast(sosx_getKsVal,pGetVar),path);
	if(Ov_Fail(result)){
		logfile_error("Could not set the getVar fb path",pobj->v_identifier);
		Finally();
		return result;
	}

	/* cycletime */
	result = fb_task_cyctime_set(Ov_DynamicPtrCast(fb_task,pGetVar),&cycletime);
	pGetVar->v_cyctimeMem = cycletime;
	pGetVar->v_timeout = 60;
	if(Ov_Fail(result)){
		logfile_error("Could not set the getVar fb cycletime",pobj->v_identifier);
		Finally();
		return result;
	}

	/* iexreq */
	pGetVar->v_iexreq = TRUE;
	pGetVar->v_sendRequested = TRUE;

	Finally();
	return result;
}

OV_RESULT  sosx_PropertyInformation_source_Cofig_SQL(
		OV_INSTPTR_sosx_PropertyInformation		pobj,
		OV_STRING								value){

	OV_INSTPTR_sosx_getHist							pGetHistFB		= NULL;
	OV_INSTPTR_ksxdrgethist_getHistParams			pGetHistParam	= NULL;
	OV_INSTPTR_ksxdrgethist_KsStringHistSelector	*pStrSel		= NULL;
	OV_RESULT										result		= OV_ERR_OK;

	OV_TIME_SPAN								cycletime	= {0,0};
	OV_UINT										memsize		= 0;
	OV_UINT										n			= 0;

	OV_STRING_VEC								strVec1		= {0,NULL};
	OV_STRING_VEC								strVec2		= {0,NULL};
	OV_STRING_VEC								strVec3		= {0,NULL};
	OV_STRING_VEC								strVec4		= {0,NULL};
	OV_STRING_VEC								strVec5		= {0,NULL};

	OV_STRING									historypath	= NULL;
	OV_STRING									orderby		= NULL;
	OV_STRING_VEC								parts		= {0,NULL};
	OV_STRING_VEC								mask		= {0,NULL};
	OV_UINT										sqlCmdFound	= 0;

#undef Finally
#define Finally()									\
		ov_string_freelist(strVec1.value);			\
		ov_string_freelist(strVec2.value);			\
		ov_string_freelist(strVec3.value);			\
		ov_string_freelist(strVec4.value);			\
		ov_string_freelist(strVec5.value);			\
		ov_string_freelist(parts.value);			\
		Ov_SetDynamicVectorLength(&mask,0,STRING);	\
		ov_string_setvalue(&historypath,NULL);		\
		ov_string_setvalue(&orderby,NULL);			\
		Ov_HeapFree(pStrSel);						\

#if OV_SYSTEM_LINUX
#define SERVERHOST "192.168.56.1"
#else
#define SERVERHOST "127.0.0.1"
#endif

#define SERVERNAME "odbcsrv_DISPO"
#define	HISTORYPATHSTUB "/Database_Values/Sichten/"

	/************************
	 * parse value
	 * get the SQL query
	 * configure getHist function block
	 *****************************/

	/*	sql:cyctime=15&memsize=10?SELECT T_Mengen,Tag FROM DYMASOS_1_Mengen WHERE Q_Anlage='O_10' AND Fraktion='PP' ORDER BY Tag ASC */

	if(!ov_string_match(value,"sql:*&*?*")){
		Finally();
		return OV_ERR_OK;
	}

	/* [0] = sql [1] = cyctime=XX&memsize=YY?SELECT T_Mengen,Tag FROM DYMASOS_1_Mengen WHERE Q_Anlage='O_10' AND Fraktion='PP' ORDER BY Tag ASC */
	strVec1.value = ov_string_split(value,":",&strVec1.veclen);
	/* [0] = cyctime=XX&memsize=YY [1] = SELECT T_Mengen,Tag FROM DYMASOS_1_Mengen WHERE Q_Anlage='O_10' AND Fraktion='PP' ORDER BY Tag ASC */
	strVec2.value = ov_string_split(strVec1.value[1],"?",&strVec2.veclen);
	/* [0] = cyctime=XX [1] = memsize=YY */
	strVec3.value = ov_string_split(strVec2.value[0],"&",&strVec3.veclen);

	/* [0] = cyctime [1] = XX *//*[0] = memsize [1] = YY */
	for(OV_UINT i=0;i<strVec3.veclen;i++){
		if(strVec4.value){
			ov_string_freelist(strVec4.value);
		}
		strVec4.value = ov_string_split(strVec3.value[i],"=",&strVec4.veclen);
		if(ov_string_compare(strVec4.value[0],"cyctime") == OV_STRCMP_EQUAL){
			cycletime.secs = atoi(strVec4.value[1]);
		} else {
			memsize = atoi(strVec4.value[1]);
		}
	}

	/* Get SQL query
	 *  SELECT T_Mengen,Tag FROM DYMASOS_1_Mengen WHERE Q_Anlage='O_10' AND Fraktion='PP' ORDER BY Tag ASC */
	strVec5.value = ov_string_split(strVec2.value[1]," ",&strVec5.veclen);
	for(OV_UINT j=0;j<strVec5.veclen;j++){
		if(ov_string_compare(strVec5.value[j],"SELECT") == OV_STRCMP_EQUAL && sqlCmdFound == 0){
			j++;
			parts.value = ov_string_split(strVec5.value[j],",",&parts.veclen);
			sqlCmdFound = 1;
			continue;
		}
		if(ov_string_compare(strVec5.value[j],"FROM") == OV_STRCMP_EQUAL && sqlCmdFound == 1){
			j++;
			ov_string_print(&historypath,"%s%s",HISTORYPATHSTUB,strVec5.value[j]);
			sqlCmdFound = 2;
			continue;
		}
		if(ov_string_compare(strVec5.value[j],"WHERE") == OV_STRCMP_EQUAL && sqlCmdFound == 2){
			j++;
			Ov_SetDynamicVectorLength(&mask,1,STRING);
			ov_string_setvalue(&mask.value[n],strVec5.value[j]);
			n++;
			sqlCmdFound = 3;
			continue;
		}
		if(ov_string_compare(strVec5.value[j],"AND") == OV_STRCMP_EQUAL && sqlCmdFound == 3){
			j++;
			Ov_SetDynamicVectorLength(&mask,n+1,STRING);
			ov_string_setvalue(&mask.value[n],strVec5.value[j]);
			n++;
			continue;
		}
		if(ov_string_compare(strVec5.value[j],"ORDER") == OV_STRCMP_EQUAL && sqlCmdFound == 3){
			j = j+2;
			ov_string_setvalue(&orderby,strVec5.value[j]);
			sqlCmdFound = 4;
			break;
		}
	}

	/* create sosx_getVar fb or update existing getVar fb if source changes */
	pGetHistFB = Ov_SearchChildEx(ov_containment,pobj,"getHistFB",sosx_getHist);
	if(pGetHistFB == NULL){
		result = Ov_CreateObject(sosx_getHist,pGetHistFB,pobj,"getHistFB");
		if(Ov_Fail(result)){
			logfile_error("Could not find or create the getHist fb ",pobj->v_identifier);
			Finally();
			return result;
		}
	}

	/*create getHistParams*/
	pGetHistParam = Ov_SearchChildEx(ov_containment,&pGetHistFB->p_apiHist,"getHistParams",ksxdrgethist_getHistParams);
	if(pGetHistParam == NULL){
		result = Ov_CreateObject(ksxdrgethist_getHistParams,pGetHistParam,&pGetHistFB->p_apiHist,"getHistParams");
		if(Ov_Fail(result)){
			Finally();
			return result;
		}
	}
	/* configure getHistParams */
	/* set */
	Ov_SetDynamicVectorLength(&pGetHistParam->v_historypaths,1,STRING);
	ov_string_setvalue(&pGetHistParam->v_historypaths.value[0],historypath);

	/* set memsize */
	pGetHistParam->v_maxanswers = memsize;
	result = sosx_PropertyInformation_memsize_set(pobj,memsize);
	if(Ov_Fail(result)){
		logfile_error("Could not set the memsize",pobj->v_identifier);
		Finally();
		return result;
	}

	pStrSel = (OV_INSTPTR_ksxdrgethist_KsStringHistSelector*)Ov_HeapMalloc(sizeof(OV_INSTPTR_ksxdrgethist_KsStringHistSelector)*parts.veclen);

	/* 1. create StringHistSelector objects
	 * 2. set part variable
	 * 3. set mask variable - odbc-Server will combine the masks of all StringHistSelector with an AND -> add special SQL-commands to the last mask
	 * */
	for(OV_UINT k=0;k<parts.veclen;k++){
		/* create StringHistSelector */
		pStrSel[k] = Ov_SearchChildEx(ov_containment,pGetHistParam,parts.value[k],ksxdrgethist_KsStringHistSelector);
		if(pStrSel[k] == NULL){
			result = Ov_CreateObject(ksxdrgethist_KsStringHistSelector,pStrSel[k],pGetHistParam,parts.value[k]);
			if(Ov_Fail(result)){
				Finally();
				return result;
			}
		}
		/* set part variable */
		ov_string_setvalue(&(pStrSel[k]->v_part),parts.value[k]);

		/* set mask variable */
		ov_string_setvalue(&pStrSel[k]->v_mask,mask.value[0]);
		for(OV_UINT l=1;l<mask.veclen;l++){
			ov_string_append(&pStrSel[k]->v_mask," AND ");
			ov_string_append(&pStrSel[k]->v_mask,mask.value[l]);
		}
	}


	/* define last object */
	Ov_Unlink(ov_containment,pGetHistParam,pStrSel[parts.veclen-1]);

	result = Ov_LinkPlaced(ov_containment,pGetHistParam,pStrSel[parts.veclen-1],OV_PMH_BEGIN);
	if(Ov_Fail(result)){
		Finally();
		return result;
	}

	if(memsize != 0 && orderby != NULL){
		ov_string_print(&pStrSel[parts.veclen-1]->v_mask,"%s<DATEADD(DAY, %i , GETDATE())",orderby,memsize);
	}

	/* complete mask of last StringHistSelector */
	if(orderby != NULL){
		ov_string_append(&pStrSel[parts.veclen-1]->v_mask," ORDER BY ");
		ov_string_append(&pStrSel[parts.veclen-1]->v_mask,orderby);
		ov_string_append(&pStrSel[parts.veclen-1]->v_mask," ASC");
	}

	/**
	 * configure FB
	 **/
	/* actimode -> stop */
	result = fb_task_actimode_set(Ov_DynamicPtrCast(fb_task,pGetHistFB),0);
	if(Ov_Fail(result)){
		logfile_error("Could not activate the getHist task ",pobj->v_identifier);
		Finally();
		return result;
	}

	/* host */
	result = sosx_getKsVal_host_set(Ov_DynamicPtrCast(sosx_getKsVal,pGetHistFB),SERVERHOST);
	if(Ov_Fail(result)){
		logfile_error("Could not set the getHist fb host ",pobj->v_identifier);
		Finally();
		return result;
	}

	/* server */
	result = sosx_getKsVal_server_set(Ov_DynamicPtrCast(sosx_getKsVal,pGetHistFB),SERVERNAME);
	if(Ov_Fail(result)){
		logfile_error("Could not set the getHist fb server ",pobj->v_identifier);
		Finally();
		return result;
	}

	/* cycletime */
	result = fb_task_cyctime_set(Ov_DynamicPtrCast(fb_task,pGetHistFB),&cycletime);
	pGetHistFB->v_cyctimeMem = cycletime;

	pGetHistFB->v_timeout = 60;
	if(Ov_Fail(result)){
		logfile_error("Could not set the getHist fb cycletime",pobj->v_identifier);
		Finally();
		return result;
	}
	/* actimode -> stop */
	result = fb_task_actimode_set(Ov_DynamicPtrCast(fb_task,pGetHistFB),0);
	if(Ov_Fail(result)){
		logfile_error("Could not activate the getHist task ",pobj->v_identifier);
		Finally();
		return result;
	}

	/* request send */
	pGetHistFB->v_sendRequested = TRUE;

	/* iexreq */
	pGetHistFB->v_iexreq = TRUE;

	Finally();
	return result;
}

OV_RESULT sosx_PropertyInformation_source_Cofig_simRes(
		OV_INSTPTR_sosx_PropertyInformation         pobj,
		OV_STRING									value

){
	OV_STRING					tmpStr			= NULL;
	OV_STRING					memsizeStr		= NULL;

	OV_RESULT		 			result 			= OV_ERR_OK;

#undef Finally
#define Finally()								\
		ov_string_setvalue(&tmpStr,NULL);		\
		ov_string_setvalue(&memsizeStr,NULL);	\

	/* schema://?query (ks://127.0.0.1/MANAGER/TechUnits/add.OUT?cyctime=5&memsize=1) */

	ov_string_setvalue(&tmpStr,value);

	/* memSize */
	result = ov_string_setvalue(&memsizeStr,strrchr(tmpStr,'=')+1);
	if(Ov_Fail(result)){
		Finally();
		return result;
	}

	/* set memsize */
	result = sosx_PropertyInformation_memsize_set(pobj,atoi(memsizeStr));
	if(Ov_Fail(result)){
		logfile_error("Could not set the memsize",pobj->v_identifier);
		Finally();
		return result;
	}

	Finally();
	return result;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_source_set(
		OV_INSTPTR_sosx_PropertyInformation          pobj,
		const OV_STRING  value
) {
	OV_RESULT 					result			= OV_ERR_OK;

#undef Finally
#define Finally()								\

	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

	/* check if string changed */
	if(!(ov_string_compare(pobj->v_source,value) != OV_STRCMP_EQUAL && value != NULL)){
		Finally();
		return result;
	}

	/* source */
	result =  ov_string_setvalue(&pobj->v_source,value);
	if(Ov_Fail(result)){
		logfile_error("Could not set the source ",pobj->v_identifier);
		Finally();
		return result;
	}

	if(value[0] == 'k' && value[1] == 's'){
		result = sosx_PropertyInformation_source_Cofig_getVar(pobj, value);
		Finally();
		return result;
	} else if (value[0] == 's' && value[1] == 'q' && value[2] == 'l'){
		result = sosx_PropertyInformation_source_Cofig_SQL(pobj, value);
		Finally();
		return result;
	}  else if (value[0] == 'o' && value[1] == 'p' && value[2] == 'c' && value[3] == 'u' && value[4] == 'a'){
		Finally();
		return OV_ERR_NOTIMPLEMENTED;
	} else if (value[0] == 's' && value[1] == 'i' && value[2] == 'm' && value[3] == 'R' && value[4] == 'e' && value[5] == 's'){
		result = sosx_PropertyInformation_source_Cofig_simRes(pobj, value);
		Finally();
		return result;
	}
	Finally();
	return result;
}

OV_DLLFNCEXPORT OV_ANY* sosx_PropertyInformation_value_get(
		OV_INSTPTR_sosx_PropertyInformation          pobj
) {
	return &pobj->v_value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_value_set(
		OV_INSTPTR_sosx_PropertyInformation          pobj,
		const OV_ANY*  value
) {
	OV_RESULT						result = OV_ERR_OK;

#undef Finally
#define Finally()

	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

	result = ov_variable_setanyvalue(&pobj->v_value, value);
	if(Ov_Fail(result)){
		Finally();
		return result;
	}

	/* add value to valVec and set timeStamp if memsize is bigger than 0 */
	if(pobj->v_memsize > 0){

		result = sosx_PropertyInformation_addValueToVec(pobj, value);
		if(Ov_Fail(result)){
			return result;
		}

		result = sosx_PropertyInformation_addTimeStamp(pobj,&value->time);
		if(Ov_Fail(result)){
			return result;
		}
		pobj->v_index++;
	}

	Finally();
	return result;
}

OV_DLLFNCEXPORT OV_STRING sosx_PropertyInformation_unit_get(
		OV_INSTPTR_sosx_PropertyInformation          pobj
) {
	return pobj->v_unit;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_unit_set(
		OV_INSTPTR_sosx_PropertyInformation          pobj,
		const OV_STRING  value
) {
	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

	return ov_string_setvalue(&pobj->v_unit,value);
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_addTimeStamp(
		OV_INSTPTR_sosx_PropertyInformation			pobj,
		const OV_TIME								*time
){
	OV_RESULT 					result 		= OV_ERR_OK;
	OV_INSTPTR_sosx_getKsVal	getKsVal	= NULL;
	OV_TIME						validFrom	= {0,0};
	OV_TIME						validUntil	= {0,0};
	OV_TIME_SPAN				cyctime		= {0,0};

	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

	/* add time stamp to the timeStamp vector */
	pobj->v_timeStamps.value[pobj->v_index] = *time;

	/* set validFrom & validUntil
	 * validFrom = oldest timeStamp in the timeStamp vector
	 * validUntil = youngest timeStamp + cycletime */
	getKsVal = Ov_SearchChildEx(ov_containment,pobj,"getVar",sosx_getKsVal);

	Ov_ForEachChildEx(ov_containment,pobj,getKsVal,sosx_getKsVal){
		if(getKsVal){
			break;
		}
	}

	if(getKsVal != NULL){
		cyctime = getKsVal->v_cyctime;
	} else if(ov_string_compare(pobj->v_type,SIMULATIONRESULT) == OV_STRCMP_EQUAL){
		cyctime = Ov_DynamicPtrCast(fb_task,ov_path_getobjectpointer("/TechUnits/sosxMngmt/executeSimulation", 2))->v_cyctime;
	}else{
		return OV_ERR_GENERIC;
	}

	if(pobj->v_timeStamps.value != NULL){

		if(pobj->v_index != pobj->v_memsize - 1 &&
				ov_time_compare(&pobj->v_timeStamps.value[pobj->v_index + 1],&validFrom) != OV_TIMECMP_EQUAL){
			validFrom = pobj->v_timeStamps.value[pobj->v_index+1];
		}else{
			validFrom = pobj->v_timeStamps.value[0];
		}
		result = sosx_BaseElement_validFrom_set(Ov_DynamicPtrCast(sosx_BaseElement,pobj),&validFrom);
		if(Ov_Fail(result)){
			return result;
		}

		/* extend valid interval */
		validUntil = *time;
		validUntil.secs = validUntil.secs + cyctime.secs;
		validUntil.usecs = validUntil.usecs +  cyctime.usecs;
		result = sosx_BaseElement_validUntil_set(Ov_DynamicPtrCast(sosx_BaseElement,pobj),&validUntil);
		if(Ov_Fail(result)){
			return result;
		}
	}

	return result;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_addValueToVec(
		OV_INSTPTR_sosx_PropertyInformation			pobj,
		const OV_ANY								*value
){
	OV_RESULT						result = OV_ERR_OK;

	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

	/* reset index if veclen is reached*/
	if(pobj->v_index == pobj->v_memsize){
		pobj->v_index = 0;
	}

	/* check if memsize is bigger than 0 */
	if(pobj->v_memsize <= 0){
		logfile_error("Memsize to small",pobj->v_identifier);
		return OV_ERR_GENERIC;
	}


	/* add value to the right vector at position index
	 * Vector length is set in the  sosx_PropertyInformation_source_set function */
	switch(value->value.vartype & OV_VT_KSMASK){
	case (OV_VT_BOOL) : {
		if(pobj->v_valueVec.value.valueunion.val_bool_vec.veclen > pobj->v_index){
			pobj->v_valueVec.value.valueunion.val_bool_vec.value[pobj->v_index] = value->value.valueunion.val_bool;
		} else {
			logfile_error("Memsize error",pobj->v_identifier);
			return OV_ERR_GENERIC;
		}}
	break;

	case (OV_VT_STRING) : {
		if(pobj->v_valueVec.value.valueunion.val_string_vec.veclen > pobj->v_index){
			ov_string_setvalue(&pobj->v_value.value.valueunion.val_string_vec.value[pobj->v_index],value->value.valueunion.val_string);
		} else {
			logfile_error("Memsize error",pobj->v_identifier);
			return OV_ERR_GENERIC;
		}}
	break;

	case (OV_VT_INT) : {
		if(pobj->v_valueVec.value.valueunion.val_int_vec.veclen > pobj->v_index){
			pobj->v_valueVec.value.valueunion.val_int_vec.value[pobj->v_index] = value->value.valueunion.val_int;
		} else {
			logfile_error("Memsize error",pobj->v_identifier);
			return OV_ERR_GENERIC;
		}}
	break;

	case (OV_VT_UINT) : {
		if(pobj->v_valueVec.value.valueunion.val_uint_vec.veclen > pobj->v_index){
			pobj->v_valueVec.value.valueunion.val_uint_vec.value[pobj->v_index] = value->value.valueunion.val_uint;
		} else {
			logfile_error("Memsize error",pobj->v_identifier);
			return OV_ERR_GENERIC;
		}}
	break;

	case (OV_VT_SINGLE) : {
		if(pobj->v_valueVec.value.valueunion.val_single_vec.veclen > pobj->v_index){
			pobj->v_valueVec.value.valueunion.val_single_vec.value[pobj->v_index] = value->value.valueunion.val_single;
		} else {
			logfile_error("Memsize error",pobj->v_identifier);
			return OV_ERR_GENERIC;
		}}
	break;

	case (OV_VT_DOUBLE) : {
		if(pobj->v_valueVec.value.valueunion.val_double_vec.veclen > pobj->v_index){
			pobj->v_valueVec.value.valueunion.val_double_vec.value[pobj->v_index] = value->value.valueunion.val_double;
		} else {
			logfile_error("Memsize error",pobj->v_identifier);
			return OV_ERR_GENERIC;
		}}
	break;

	//TODO: define error value that is set in case of communication failure
	case (OV_VT_VOID) : break;  // communication failed -> store timeStamp only

	default :
		logfile_error("unknown datatype",pobj->v_identifier);
		return OV_ERR_BADTYPE;
	}

	return result;
}

OV_DLLFNCEXPORT OV_RESULT sosx_PropertyInformation_constructor(
		OV_INSTPTR_ov_object 	pobj
) {
	/*
	 *   local variables
	 */
	// OV_INSTPTR_sosx_PropertyInformation pinst = Ov_StaticPtrCast(sosx_PropertyInformation, pobj);
	OV_RESULT    result;

	/* do what the base class does first */
	result = ov_object_constructor(pobj);
	if(Ov_Fail(result))
		return result;

	/* do what */


	return OV_ERR_OK;
}

