
/******************************************************************************
 *
 *   FILE
 *   ----
 *   SourceSink.c
 *
 *   History
 *   -------
 *   2014-10-23   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"



OV_DLLFNCEXPORT OV_UINT sosx_SourceSink_sourceSinkType_get(
		OV_INSTPTR_sosx_SourceSink          pobj
) {
	OV_INSTPTR_sosx_Stream		pStream;

	/* check if pobj is input
	 * 1. Check if SideA is connected to a Stream */

	pStream = Ov_GetFirstChild(sosx_isLinkedToSideA, pobj);
	if(pStream != NULL)
	{
		pobj->v_sourceSinkType = 1;
		return pobj->v_sourceSinkType;
	}
	/* check if pobj is output
	 * 1. Check if SideB is connected to a Stream */
	pStream = Ov_GetFirstChild(sosx_isLinkedToSideB, pobj);
	if(pStream != NULL)
	{
		pobj->v_sourceSinkType = 0;
		return pobj->v_sourceSinkType;
	}
	/*sourceSink is not input or output*/
	pobj->v_sourceSinkType = 2;
	return pobj->v_sourceSinkType;
	return pobj->v_sourceSinkType;
}

OV_DLLFNCEXPORT OV_RESULT sosx_SourceSink_constructor(
		OV_INSTPTR_ov_object 	pobj
) {
	/*
	 *   local variables
	 */
	// OV_INSTPTR_sosx_SourceSink pinst = Ov_StaticPtrCast(sosx_SourceSink, pobj);
	OV_RESULT    result;

	/* do what the base class does first */
	result = ov_object_constructor(pobj);
	if(Ov_Fail(result))
		return result;

	/* do what */


	return OV_ERR_OK;
}

