
/******************************************************************************
*
*   FILE
*   ----
*   Property.c
*
*   History
*   -------
*   2014-11-29   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_STRING sosx_Property_name_get(
    OV_INSTPTR_sosx_Property          pobj
) {
    return pobj->v_name;
}

OV_DLLFNCEXPORT OV_RESULT sosx_Property_name_set(
    OV_INSTPTR_sosx_Property          pobj,
    const OV_STRING  value
) {
	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

    return ov_string_setvalue(&pobj->v_name,value);
}

OV_DLLFNCEXPORT OV_RESULT sosx_Property_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    // OV_INSTPTR_sosx_Property pinst = Ov_StaticPtrCast(sosx_Property, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

