
/******************************************************************************
*
*   FILE
*   ----
*   Port.c
*
*   History
*   -------
*   2014-10-23   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"




OV_DLLFNCEXPORT OV_STRING sosx_Port_StreamType_get(
    OV_INSTPTR_sosx_Port          pobj
) {
    return pobj->v_StreamType;
}

OV_DLLFNCEXPORT OV_RESULT sosx_Port_StreamType_set(
    OV_INSTPTR_sosx_Port          pobj,
    const OV_STRING  value
) {
	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

    return ov_string_setvalue(&pobj->v_StreamType,value);
}

OV_DLLFNCEXPORT OV_UINT sosx_Port_portType_get(
    OV_INSTPTR_sosx_Port          pobj
) {
	OV_INSTPTR_sosx_Stream		pStream;
	OV_INSTPTR_ov_domain		pPortParent;
	OV_INSTPTR_ov_domain		pStreamParent;

	/* check if pobj is input
	 * 1. Check if SideA is connected to a Stream
	 * 2. Check if Parent of Port and Stream are not the same */

	pStream = Ov_GetFirstChild(sosx_isLinkedToSideA, pobj);
	if(pStream != NULL)
	{
		pPortParent = Ov_GetParent(ov_containment, pobj);
		pStreamParent = Ov_GetParent(ov_containment, pStream);
		if(pPortParent != pStreamParent)
		{
			pobj->v_portType = 1;
			return pobj->v_portType;
		}
	}
	/* check if pobj is Output
		 * 1. Check if SideB is connected to a Stream
		 * 2. Check if Parent of Stream and Stream are not the same */
	pStream = Ov_GetFirstChild(sosx_isLinkedToSideB, pobj);
		if(pStream != NULL)
		{
			pPortParent = Ov_GetParent(ov_containment, pobj);
			pStreamParent = Ov_GetParent(ov_containment, pStream);
			if(pPortParent != pStreamParent)
			{
				pobj->v_portType = 0;
				return pobj->v_portType;
			}
		}
		/*port is not input or output*/
		pobj->v_portType = 2;
    return pobj->v_portType;
}


OV_DLLFNCEXPORT OV_RESULT sosx_Port_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    // OV_INSTPTR_sosx_Port pinst = Ov_StaticPtrCast(sosx_Port, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

