
/******************************************************************************
 *
 *   FILE
 *   ----
 *   SoSContainer.c
 *
 *   History
 *   -------
 *   2015-01-26   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"


OV_DLLFNCEXPORT OV_STRING sosx_SoSContainer_name_get(
		OV_INSTPTR_sosx_SoSContainer          pobj
) {
	return pobj->v_name;
}

OV_DLLFNCEXPORT OV_RESULT sosx_SoSContainer_name_set(
    OV_INSTPTR_sosx_SoSContainer          pobj,
    const OV_STRING  value
) {
	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

    return ov_string_setvalue(&pobj->v_name,value);
}


//OV_DLLFNCEXPORT OV_RESULT sosx_SoSContainer_name_set(
//		OV_INSTPTR_sosx_SoSContainer          pobj,
//		const OV_STRING  value
//) {
//	OV_INSTPTR_sosx_sosxdomain pDomain = NULL;
//	if(pobj){//(pchild)
//		if(pobj->v_linktable){ //(pchild)->v_linktable
//			if(passoc_ov_instantiation->v_assoctype==OV_AT_ONE_TO_MANY){ //passoc_##assoc->v_assoctype==OV_AT_ONE_TO_MANY
//				pDomain = (OV_INSTPTR_sosx_sosxdomain)
//						(((OV_ANCHOR*)((pobj)->v_linktable+passoc_ov_instantiation->v_childoffset
//								+((pobj)->__classinfo.is_of_class_ov_object)
//								-((pobj)->__classinfo.is_of_class_ov_object)))->pparent);
//			} else { // 1:1 assoziation
//				pDomain = (OV_INSTPTR_sosx_sosxdomain) (*((OV_INSTPTR*)((pobj)->v_linktable+passoc_ov_instantiation->v_childoffset)));
//			}
//		} else {	// erstes NULL in GetParent
//			pDomain = NULL;
//		}
//	} else {	//letztes NULL in GetParent
//		pDomain = NULL;
//	}
//	if(!pDomain){	// letzter Teil von ov_class_cancastto
//		if(ov_class_cancastto(Ov_GetParent(ov_instantiation, (pobj)), pclass_sosx_sosxdomain)){
//			pDomain = (OV_INSTPTR_sosx_sosxdomain) pobj;
//		}
//	}
//	sosx_sosxdomain_restIsValidIfValueChanged(pDomain);
//
//	return ov_string_setvalue(&pobj->v_name,value);
//}

OV_DLLFNCEXPORT OV_STRING* sosx_SoSContainer_externalReference_get(
		OV_INSTPTR_sosx_SoSContainer          pobj,
		OV_UINT *pveclen
) {
	*pveclen = pobj->v_externalReference.veclen;
	return pobj->v_externalReference.value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_SoSContainer_externalReference_set(
		OV_INSTPTR_sosx_SoSContainer          pobj,
		const OV_STRING*  value,
		const OV_UINT veclen
) {
	sosx_sosxdomain_restIsValidIfValueChanged(Ov_DynamicPtrCast(sosx_sosxdomain,pobj));

	return Ov_SetDynamicVectorValue(&pobj->v_externalReference,value,veclen,STRING);
}

OV_DLLFNCEXPORT OV_RESULT sosx_SoSContainer_constructor(
		OV_INSTPTR_ov_object 	pobj
) {
	/*
	 *   local variables
	 */
	// OV_INSTPTR_sosx_SoSContainer pinst = Ov_StaticPtrCast(sosx_SoSContainer, pobj);
	OV_RESULT    result;

	/* do what the base class does first */
	result = ov_object_constructor(pobj);
	if(Ov_Fail(result))
		return result;

	/* do what */


	return OV_ERR_OK;
}

