
/******************************************************************************
*
*   FILE
*   ----
*   System.c
*
*   History
*   -------
*   2014-10-23   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif

#include "sosx.h"
#include "libov/ov_macros.h"

OV_DLLFNCEXPORT OV_RESULT sosx_System_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
    // OV_INSTPTR_sosx_System pinst = Ov_StaticPtrCast(sosx_System, pobj);
    OV_RESULT    result;

    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;

    /* do what */


    return OV_ERR_OK;
}

