
/******************************************************************************
 *
 *   FILE
 *   ----
 *   executeSimulation.c
 *
 *   History
 *   -------
 *   2016-07-09   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"
#include "sosxcommon.h"
#include "libov/ov_result.h"

#if OV_SYSTEM_NT
#include  "io.h"
#endif

#if !OV_SYSTEM_NT
#include <unistd.h>
#endif

OV_DLLFNCEXPORT OV_STRING sosx_executeSimulation_CeaxArchiveDir_get(
		OV_INSTPTR_sosx_executeSimulation          pobj
) {
	return pobj->v_CeaxArchiveDir;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_CeaxArchiveDir_set(
		OV_INSTPTR_sosx_executeSimulation          pobj,
		const OV_STRING  value
) {
	return ov_string_setvalue(&pobj->v_CeaxArchiveDir,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_executeSimulation_lastFileName_get(
		OV_INSTPTR_sosx_executeSimulation          pobj
) {
	return pobj->v_lastFileName;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_lastFileName_set(
		OV_INSTPTR_sosx_executeSimulation          pobj,
		const OV_STRING  value
) {
	return ov_string_setvalue(&pobj->v_lastFileName,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_executeSimulation_simCmd_get(
		OV_INSTPTR_sosx_executeSimulation          pobj
) {
	return pobj->v_simCmd;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_simCmd_set(
		OV_INSTPTR_sosx_executeSimulation          pobj,
		const OV_STRING  value
) {
	return ov_string_setvalue(&pobj->v_simCmd,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_executeSimulation_SosxStruct_get(
		OV_INSTPTR_sosx_executeSimulation          pobj
) {
	return pobj->v_SosxStruct;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_SosxStruct_set(
		OV_INSTPTR_sosx_executeSimulation          pobj,
		const OV_STRING  value
) {
	return ov_string_setvalue(&pobj->v_SosxStruct,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_executeSimulation_lastCeaxSimFile_get(
		OV_INSTPTR_sosx_executeSimulation          pobj
) {
	return pobj->v_lastCeaxSimFile;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_lastCeaxSimFile_set(
		OV_INSTPTR_sosx_executeSimulation          pobj,
		const OV_STRING  value
) {
	return ov_string_setvalue(&pobj->v_lastCeaxSimFile,value);
}

OV_DLLFNCEXPORT OV_BOOL sosx_executeSimulation_CreateCeaxFile_get(
		OV_INSTPTR_sosx_executeSimulation          pobj
) {
	return pobj->v_CreateCeaxFile;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_CreateCeaxFile_set(
		OV_INSTPTR_sosx_executeSimulation          pobj,
		const OV_BOOL  value
) {
	pobj->v_CreateCeaxFile = value;
	return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_STRING sosx_executeSimulation_SimDir_get(
		OV_INSTPTR_sosx_executeSimulation          pobj
) {
	return pobj->v_SimDir;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_SimDir_set(
		OV_INSTPTR_sosx_executeSimulation          pobj,
		const OV_STRING  value
) {
	return ov_string_setvalue(&pobj->v_SimDir,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_executeSimulation_SimResDir_get(
		OV_INSTPTR_sosx_executeSimulation          pobj
) {
	return pobj->v_SimResDir;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_SimResDir_set(
		OV_INSTPTR_sosx_executeSimulation          pobj,
		const OV_STRING  value
) {
	return ov_string_setvalue(&pobj->v_SimResDir,value);
}

OV_DLLFNCEXPORT void sosx_executeSimulation_typemethod(
		OV_INSTPTR_fb_functionblock	pfb,
		OV_TIME						*pltc
) {
	OV_RESULT							result 			= OV_ERR_OK;
	OV_INT								sysresult		= 0;
	OV_STRING							cmd				= NULL;
	OV_STRING							srcFileName		= NULL;
	OV_STRING							trgtFileName	= NULL;
	OV_STRING							fileName		= NULL;
	OV_STRING							fileNameRes		= NULL;

	OV_STRING_VEC						simResCaex		= {0,NULL};
	OV_STRING_VEC						SimResName		= {0,NULL};

	OV_BOOL								ResFileWasLoaded	= FALSE;
	char								ch;
	FILE*								srcFile;
	FILE*								trgtFile;

	OV_INSTPTR_ov_domain				pCaex			= (OV_INSTPTR_ov_domain)ov_path_getobjectpointer("/TechUnits/ImportExport/CAEX", 2);
	OV_INSTPTR_ov_domain				pSosx			= (OV_INSTPTR_ov_domain)ov_path_getobjectpointer("/TechUnits/sosx", 2);
	OV_INSTPTR_caex_CAEXFile			pCaexFile		= NULL;
	OV_INSTPTR_ov_domain				pSoSStruct		= NULL;

	OV_INSTPTR_sosx_executeSimulation	pinst 			= Ov_StaticPtrCast(sosx_executeSimulation, pfb);

#undef Finally
#define Finally()										\
		ov_string_setvalue(&cmd,NULL);					\
		ov_string_setvalue(&srcFileName,NULL);			\
		ov_string_setvalue(&trgtFileName,NULL);			\
		ov_string_setvalue(&fileName,NULL);				\
		ov_string_setvalue(&fileNameRes,NULL);			\
		Ov_SetDynamicVectorLength(&simResCaex,0,STRING);\
		if(SimResName.veclen > 0){						\
			ov_string_freelist(SimResName.value);}		\

	logfile_debug("Execute Simulation started at ",ov_time_timetoascii_local(pltc));

	/* check configuration of the fb*/
	if(ov_string_compare(pinst->v_SimDir,"")==OV_STRCMP_EQUAL ||
			(ov_string_compare(pinst->v_lastFileName,"")==OV_STRCMP_EQUAL && !pinst->v_CreateCeaxFile) ||
			ov_string_compare(pinst->v_simCmd,"")==OV_STRCMP_EQUAL ||
			!pCaex ||
			!pSosx){
		logfile_error("Input missing ","please set a value for SimFolder, lastFileName and simCmd");
		Finally();
		return;
	}

	/* get pointer to the rootelement of the SoSx structure in the Sosx domain*/
	Ov_ForEachChildEx(ov_containment,pSosx,pSoSStruct,ov_domain){
		if(ov_string_compare(pSoSStruct->v_identifier,pinst->v_SosxStruct) == OV_STRCMP_EQUAL){
			break;
		}
	}

if(!pSoSStruct){
	logfile_error("Could not find the SoSStruct. ","Please check the configuration." );
	return;
}

	/* 1. Check if update file was loaded during last execution
	 * 2. update
	 * 3. Remove update file and delete update struct afterwards
	 * 4. export current State into CAEXArchiveDir
	 * 5. copy exported state file into SimFolder
	 * 6. Execute Simulation
	 * 7. Find most recent simulation result
	 * 8. Trigger import of simulation result file
	 */

	/* Check if update file was loaded during last execution */
	Ov_ForEachChildEx(ov_containment,pCaex,pCaexFile,caex_CAEXFile){
		if(ov_string_match(pCaexFile->v_identifier,"*_SimRes.export")){
			ResFileWasLoaded = TRUE;
			log_debug("Update available, will start update now");
			break;
		}
	}


	/* use result file for an update */
	if(ResFileWasLoaded){
		/* update */
		result = sosx_workflowManagement_updateElement(pSoSStruct,Ov_DynamicPtrCast(caex_CAEXBasicObject,pCaexFile),SOSX_UPDATE_SIMRESONLY);
		if(Ov_Fail(result)){
			logfile_error("Could not update. Reason: ", ov_result_getresulttext(result));
		}
		/* delete */
		result = Ov_DeleteObject(pCaexFile);
		if(Ov_Fail(result)){
			logfile_error("Could not delete update structure. Reason: ", ov_result_getresulttext(result));
		}
	}



	/* create Filename */
	createExportName(pSoSStruct->v_identifier,&fileName,pltc);

	/* export file */
	if(pinst->v_CreateCeaxFile){
		result = sosx_workflowManagement_exportCaexFile(pSoSStruct,pinst->v_CeaxArchiveDir,fileName,TRUE);
		if(Ov_Fail(result)){
			logfile_error("Could not export Caex file . Reason: ", ov_result_getresulttext(result));
			Finally();
			return;
		}
	}

	/* copy latest file into the simulation folder
	 * simulation will delete file once done with it */

	/* create FileNames and transfer file */
	ov_string_print(&srcFileName,"%s%s%s",pinst->v_CeaxArchiveDir,"\\",pinst->v_lastFileName);
	ov_string_print(&trgtFileName,"%s%s%s",pinst->v_SimDir,"\\",pinst->v_lastFileName);

	/*check if source and target are equal*/
	if(ov_string_compare(srcFileName,trgtFileName) == OV_STRCMP_EQUAL){
		logfile_error("Source and Target file are equal",srcFileName);
		trgtFile= fopen(trgtFileName,"w");
		fputs("CaexOutFolder and SimFolder should not be the same!",trgtFile);
		Finally();
		return;
	}

	/* check if source exists */
#if OV_SYSTEM_NT
	if( _access(srcFileName , 00 ) == -1 ) {
		/* srcFile Does not exist -> return  */
		logfile_error("Could not find the file:",srcFileName);
		Finally();
		return;
	}
#endif

#if !OV_SYSTEM_NT
	if( access(srcFileName , 00 ) == -1 ) {
		/* srcFile Does not exist -> return  */
		logfile_error("Could not find the file:",srcFileName);
		Finally();
		return;
	}
#endif

	/* copy file */
	srcFile = fopen(srcFileName,"r");
	trgtFile= fopen(trgtFileName,"w");

	while((ch = fgetc(srcFile)) != EOF){
		fputc(ch,trgtFile);
	}

	fclose(srcFile);
	fclose(trgtFile);
	/* start simulation */
	/* create CMD */
	ov_string_print(&cmd,"%s%s%s%s"," start \"ExecutingSimulation\" /D ",pinst->v_SimDir," ",pinst->v_simCmd);

	logfile_debug("Calling simulation at: ",ov_time_timetoascii_local(pltc));

	/* execute command */
	sysresult = system(cmd);

	if(sysresult != 0){
		log_error("Could not execute the simulation");
	}

	/* find most recent sim result */
	if(pinst->v_lastCeaxSimFile){
		SimResName.value = ov_string_split(pinst->v_lastCeaxSimFile,".",&SimResName.veclen);
		ov_string_print(&fileNameRes,"%s%s",SimResName.value[0],"_SimRes.export");

		/* trigger import of most recent sim result */
		Ov_SetDynamicVectorLength(&simResCaex,1,STRING);
		ov_string_setvalue(&simResCaex.value[0],fileNameRes);
		result = sosx_workflowManagement_importCaexFile(pinst->v_SimResDir,simResCaex);
		if(Ov_Fail(result)){
			logfile_error("Could not import Caex file . Reason: ", ov_result_getresulttext(result));
			Finally();
			return;
		}
	}

	ov_string_setvalue(&pinst->v_lastCeaxSimFile,fileName);

	Finally();
	return;
}

OV_DLLFNCEXPORT OV_RESULT sosx_executeSimulation_constructor(
		OV_INSTPTR_ov_object 	pobj
) {
	/*
	 *   local variables
	 */
	OV_INSTPTR_sosx_executeSimulation pinst = Ov_StaticPtrCast(sosx_executeSimulation, pobj);
	OV_RESULT    result;

	/* do what the base class does first */
	result = fb_functionblock_constructor(pobj);
	if(Ov_Fail(result))
		return result;

	/* do what */

	pinst->v_iexreq = TRUE;

	// link to task
	result = Ov_Link(fb_tasklist,Ov_DynamicPtrCast(fb_task,ov_path_getobjectpointer("/Tasks/UrTask",2)),Ov_DynamicPtrCast(fb_task,pinst));
	if(Ov_Fail(result)){
		return result;
	}

	return OV_ERR_OK;
}

