
/******************************************************************************
 *
 *   FILE
 *   ----
 *   exportCaexFb.c
 *
 *   History
 *   -------
 *   2016-06-13   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"
#include "sosxcommon.h"


OV_DLLFNCEXPORT OV_STRING sosx_exportCaexFb_target_get(
		OV_INSTPTR_sosx_exportCaexFb          pobj
) {
	return pobj->v_target;
}

OV_DLLFNCEXPORT OV_RESULT sosx_exportCaexFb_target_set(
		OV_INSTPTR_sosx_exportCaexFb          pobj,
		const OV_STRING  value
) {
	return ov_string_setvalue(&pobj->v_target,value);
}

OV_DLLFNCEXPORT OV_STRING sosx_exportCaexFb_source_get(
		OV_INSTPTR_sosx_exportCaexFb          pobj
) {
	return pobj->v_source;
}

OV_DLLFNCEXPORT OV_RESULT sosx_exportCaexFb_source_set(
		OV_INSTPTR_sosx_exportCaexFb          pobj,
		const OV_STRING  value
) {
	return ov_string_setvalue(&pobj->v_source,value);
}

OV_DLLFNCEXPORT void sosx_exportCaexFb_typemethod(
		OV_INSTPTR_fb_functionblock	pfb,
		OV_TIME						*pltc
) {
	OV_RESULT 						result				= OV_ERR_OK;
	OV_INSTPTR_ov_domain			ptarget				= NULL;
	OV_INSTPTR_ov_domain			pSOSX				= NULL;
	OV_STRING_VEC					PathToSourceList 	= {0,NULL};
	OV_STRING						Name				= NULL;

	OV_INSTPTR_sosx_exportCaexFb	pinst 				= Ov_StaticPtrCast(sosx_exportCaexFb, pfb);

#undef Finally
#define Finally()											\
		if(PathToSourceList.value){							\
			ov_string_freelist(PathToSourceList.value);}	\
			ov_string_setvalue(&Name,NULL);					\



	if(pinst->v_source == NULL || pinst->v_target == NULL){
		return;
	}

	/* find sosx container */
	pSOSX = (OV_INSTPTR_ov_domain)ov_path_getobjectpointer("/TechUnits/sosx", 2);
	if ((pSOSX == NULL)){
		log_error("Cannot find domain sosx. Please create Instanz-Container 'TechUnits/sosx'");
		Finally();
		return;
	}

	/* find target object*/
	PathToSourceList.value = ov_string_split(pinst->v_source,"/",&PathToSourceList.veclen);
	ptarget = pSOSX;
	for (OV_UINT u = 0; u < PathToSourceList.veclen; u++){
		ptarget = Ov_SearchChildEx(ov_containment,ptarget,PathToSourceList.value[u],ov_domain);
		if(ptarget == NULL){
			log_error("Cannot find the Source");
			Finally();
			return;
		}
	}

	createExportName(PathToSourceList.value[ PathToSourceList.veclen-1],&Name,pltc);

	/*export CEAX file */
	result = sosx_workflowManagement_exportCaexFile(ptarget,pinst->v_target, Name, FALSE);
	if(Ov_Fail(result)){
		logfile_error("Could not export: ", pinst->v_target);
	}

	Finally();
	return;
}

OV_DLLFNCEXPORT OV_RESULT sosx_exportCaexFb_constructor(
		OV_INSTPTR_ov_object 	pobj
) {
	/*
	 *   local variables
	 */
	OV_INSTPTR_sosx_exportCaexFb pinst = Ov_StaticPtrCast(sosx_exportCaexFb, pobj);
	OV_RESULT    result;

	/* do what the base class does first */
	result = fb_functionblock_constructor(pobj);
	if(Ov_Fail(result))
		return result;

	/* do what */

	// link to task
	result = Ov_Link(fb_tasklist,Ov_DynamicPtrCast(fb_task,ov_path_getobjectpointer("/Tasks/UrTask",2)),Ov_DynamicPtrCast(fb_task,pinst));
	if(Ov_Fail(result)){
		return result;
	}

	return OV_ERR_OK;
}

