
/******************************************************************************
 *
 *   FILE
 *   ----
 *   FileMonitor.c
 *
 *   History
 *   -------
 *   2015-09-27   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif

#include "sosx.h"
#include "libov/ov_macros.h"
#include "stdio.h"
#include "sys/stat.h"
#include "libov/ov_logfile.h"
#include "limits.h"
#include "libov/ov_path.h"

#if OV_SYSTEM_NT
#include  "io.h"
#endif

#if !OV_SYSTEM_NT
#include <unistd.h>
#endif

OV_DLLFNCEXPORT OV_RESULT sosx_FileMonitor_filePath_set(
		OV_INSTPTR_sosx_FileMonitor          pobj,
		const OV_STRING*  value,
		const OV_UINT veclen
) {
	OV_BOOL				found			= FALSE;
	OV_INT_VEC			fileDateTemp	= {0,NULL};
	OV_RESULT			result			= OV_ERR_OK;

	Ov_SetDynamicVectorLength(&fileDateTemp,veclen,INT);

	for(OV_UINT i = 0; i<veclen ;i++){
		for(OV_UINT j = 0; j<pobj->v_filePath.veclen ;j++){
			if(ov_string_compare(value[i],pobj->v_filePath.value[j]) == OV_STRCMP_EQUAL){
				// match the other two vectors if user change the order
				found = TRUE;
				fileDateTemp.value[i] = pobj->v_filedate.value[j];
			} else {
				found = FALSE;
			}
		}
		if(!found){
			// set other two vectors to default value if user added new externalInfo
			fileDateTemp.value[i] = INT32_MIN;
		}
	}
	Ov_SetDynamicVectorValue(&pobj->v_filedate,&fileDateTemp.value,fileDateTemp.veclen,INT);

	// set filePath
	result = Ov_SetDynamicVectorValue(&pobj->v_filePath,value,veclen,STRING);
	if(Ov_Fail(result)){
		return result;
	}

	// force execution of fb
	pobj->v_execute = TRUE;

	return result;
}

OV_DLLFNCEXPORT OV_RESULT sosx_FileMonitor_hasChanged_set(
		OV_INSTPTR_sosx_FileMonitor          pobj,
		const OV_UINT*  value,
		const OV_UINT veclen
) {
	OV_INSTPTR_ov_domain		pParent		= NULL;

	pParent = Ov_GetParent(ov_containment,pobj);

	Ov_SetDynamicVectorValue(&Ov_DynamicPtrCast(sosx_Process,pParent)->v_externalInfoStat,value,veclen,UINT);

	return Ov_SetDynamicVectorValue(&pobj->v_hasChanged,value,veclen,UINT);
}

OV_DLLFNCEXPORT OV_UINT* sosx_FileMonitor_hasChanged_get(
		OV_INSTPTR_sosx_FileMonitor          pobj,
		OV_UINT *pveclen
) {
	*pveclen = pobj->v_hasChanged.veclen;
	return pobj->v_hasChanged.value;
}

OV_DLLFNCEXPORT OV_RESULT sosx_FileMonitor_reset_set(
		OV_INSTPTR_sosx_FileMonitor          pobj,
		const OV_BOOL*  value,
		const OV_UINT veclen
) {
	OV_RESULT			result			= OV_ERR_OK;

	result = Ov_SetDynamicVectorValue(&pobj->v_reset,value,veclen,BOOL);
	if(Ov_Fail(result)){
		return result;
	}

	// force execution of fb
	pobj->v_execute = TRUE;

	return result;
}

OV_DLLFNCEXPORT OV_RESULT sosx_FileMonitor_exCycTime_set(
		OV_INSTPTR_sosx_FileMonitor          pobj,
		const OV_TIME_SPAN*  value
) {
	pobj->v_exCycTime = *value;
	return OV_ERR_OK;
}

OV_DLLFNCEXPORT OV_RESULT sosx_FileMonitor_execute_set(
		OV_INSTPTR_sosx_FileMonitor          pobj,
		const OV_BOOL  value
) {
	pobj->v_execute = value;
	return OV_ERR_OK;
}

OV_DLLFNCEXPORT void sosx_FileMonitor_typemethod(
		OV_INSTPTR_fb_functionblock	pfb,
		OV_TIME						*pltc
) {
	struct stat stResult;
	const struct stat Empty;

	OV_TIME			someTimeAgo 	= {0,0};
	OV_UINT_VEC		hasChangedTemp	= {0,NULL};

	OV_INSTPTR_sosx_FileMonitor pinst = Ov_StaticPtrCast(sosx_FileMonitor, pfb);

	ov_time_gettime(&someTimeAgo);
	someTimeAgo.secs = someTimeAgo.secs - pinst->v_exCycTime.secs;
	someTimeAgo.usecs = someTimeAgo.usecs - pinst->v_exCycTime.usecs;

	if(pinst->v_execute || ov_time_compare(&pinst->v_lastExecutionTime,&someTimeAgo) != OV_TIMECMP_AFTER){
		pinst->v_lastExecutionTime = *pltc;
		pinst->v_execute = FALSE;

		Ov_SetDynamicVectorLength(&hasChangedTemp,pinst->v_filePath.veclen,UINT);

		// go through file list
		for(OV_UINT i = 0;i < pinst->v_filePath.veclen;i++){

			// Reset stResult;
			stResult = Empty;

			// Reset for the case that the variable setter was not called.
			if (pinst->v_reset.value[i]){
				hasChangedTemp.value[i] = SOSX_EXTERNALINFOSTATE_NOTCHECKED;
			}

			// If no file path is configured we are done.
			if (pinst->v_filePath.value[i] == NULL){
				break;
			}

			// Reset the 'reset' input.
			pinst->v_reset.value[i] = FALSE;

#if OV_SYSTEM_NT
			// Check if the file exists
			if( _access(pinst->v_filePath.value[i] , 00 ) == -1 ) {
				/* file does not exist */
				ov_logfile_info("File Monitor: Cannot find the folder %s.",pinst->v_filePath.value[i]);
				hasChangedTemp.value[i] = SOSX_EXTERNALINFOSTATE_NOTFOUND;
				break;
			}
#endif

#if !OV_SYSTEM_NT
			// Check if the file exists
			if( access(pinst->v_filePath.value[i] , 00 ) == -1 ) {
				/* file does not exist */
				ov_logfile_info("File Monitor: Cannot find the folder %s.",pinst->v_filePath.value[i]);
				hasChangedTemp.value[i] = SOSX_EXTERNALINFOSTATE_NOTFOUND;
				break;
			}
#endif


			// Try to get the file info.
			if(stat(pinst->v_filePath.value[i], &stResult)!=0){
				ov_logfile_info("FileMonitor: Unable to get file information for %s.", pinst->v_filePath.value[i]);
				break;
			}

			// Set the initial value, if necessary.
			if (pinst->v_filedate.value[i] == INT32_MIN){
				pinst->v_filedate.value[i] = stResult.st_mtime;
				break;
			}

			// Check if file has changed.
			if (stResult.st_mtime > pinst->v_filedate.value[i]){
				hasChangedTemp.value[i] = SOSX_EXTERNALINFOSTATE_CHANGED;
				pinst->v_filedate.value[i] = stResult.st_mtime;
			} else {
				hasChangedTemp.value[i] = SOSX_EXTERNALINFOSTATE_NOCHANGE;
			}
		}

		// push results
		sosx_FileMonitor_hasChanged_set(pinst,hasChangedTemp.value,hasChangedTemp.veclen);
	}
	return;
}

OV_DLLFNCEXPORT OV_RESULT sosx_FileMonitor_constructor(
		OV_INSTPTR_ov_object 	pobj
) {
	/*
	 *   local variables
	 */
	OV_INSTPTR_sosx_FileMonitor pinst = Ov_StaticPtrCast(sosx_FileMonitor, pobj);
	OV_RESULT    								result 			= OV_ERR_OK;


	/* do what the base class does first */
	result = fb_functionblock_constructor(pobj);
	if(Ov_Fail(result))
		return result;

	// link to task
	result = Ov_Link(fb_tasklist,Ov_DynamicPtrCast(fb_task,ov_path_getobjectpointer("/Tasks/UrTask",2)),Ov_DynamicPtrCast(fb_task,pinst));
	if(Ov_Fail(result)){
		return result;
	}

	// set cycle time
	pinst->v_cyctime.secs = 1;

	pinst->v_exCycTime.secs = 300;

	// set actimode
	pinst->v_actimode = 1;

	return result;
}

