
/******************************************************************************
 *
 *   FILE
 *   ----
 *   getHist.c
 *
 *   History
 *   -------
 *   2016-04-29   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif


#include "sosx.h"
#include "libov/ov_macros.h"
#include "libov/ov_path.h"
#include "sosxcommon.h"
#include "ksapi_commonFuncs.h"
#include "config.h" /* fbcomlib*/



OV_DLLFNCEXPORT OV_RESULT sosx_getHist_constructor(
		OV_INSTPTR_ov_object 	pobj
) {
	/*
	 *   local variables
	 */
	//OV_INSTPTR_sosx_getHist pinst = Ov_StaticPtrCast(sosx_getHist, pobj);
	OV_RESULT    result;

	/* do what the base class does first */
	result = sosx_getKsVal_constructor(pobj);
	if(Ov_Fail(result))
		return result;

	/* do what */


	return OV_ERR_OK;
}

OV_DLLFNCEXPORT void sosx_getHist_startup(
		OV_INSTPTR_ov_object 	pobj
) {
	/*
	 *   local variables
	 */
	//OV_INSTPTR_sosx_getHist pinst = Ov_StaticPtrCast(sosx_getHist, pobj);

	/* do what the base class does first */
	sosx_getKsVal_startup(pobj);

	/* do what */


	return;
}

OV_DLLFNCEXPORT void sosx_getHist_typemethod(
		OV_INSTPTR_fb_functionblock	pfb,
		OV_TIME						*pltc
) {
	/*
	 *   local variables
	 */
	OV_INSTPTR_sosx_getHist							pinstGetHist			= Ov_StaticPtrCast(sosx_getHist, pfb);
	OV_INSTPTR_sosx_getKsVal 						pinst					= Ov_StaticPtrCast(sosx_getKsVal, pfb);
	OV_INSTPTR_ov_domain							pPropertyInfo			= Ov_GetParent(ov_containment,pfb);
	OV_INSTPTR_ksxdrgethist_GetHistResult			pHistResult				= NULL;
	OV_INSTPTR_ksxdrgethist_KsGetHistPerHistResult	pGetHistPerHistResult	= NULL;
	OV_INSTPTR_ksxdrgethist_KsGetHistResultItem		pKsGetHistResultItem	= NULL;
	OV_VTBLPTR_ksxdrgethist_getHist					pVtblGetHist 			= (OV_VTBLPTR_ksxdrgethist_getHist) pclass_ksxdrgethist_getHist->v_pvtable;
	OV_TIME_VEC										tempTimeVec				= {0,NULL};
	OV_RESULT 										result					= OV_ERR_OK;

#undef Finally
#define Finally()									\
		Ov_SetDynamicVectorLength(&tempTimeVec,0,TIME);	\

	////////////////////////////////////////////////////////////////////
	//logfile_info("Executing get hist for ",pPropertyInfo->v_identifier);
	////////////////////////////////////////////////////////////////////

	if(pinst->v_state == FBCOMLIB_STATE_WAITING)
	{	/*	waiting: calculate timeouts and check ksapi-object for answer	*/

		/* count seconds in state waiting */
		pinstGetHist->v_waitStateCount++;

		if(pinstGetHist->p_apiHist.v_status == KSAPI_COMMON_REQUESTCOMPLETED)
		{	/*	ksapi-request completed --> get answer	*/
			pinst->v_opResult = pinstGetHist->p_apiHist.v_result;
			pinst->v_varResult = pinstGetHist->p_apiHist.v_status;

			pHistResult = Ov_SearchChildEx(ov_containment,&pinstGetHist->p_apiHist,"GetHistResult", ksxdrgethist_GetHistResult);
			Ov_ForEachChildEx(ov_containment,pHistResult,pGetHistPerHistResult,ksxdrgethist_KsGetHistPerHistResult){

				if(pGetHistPerHistResult == NULL || Ov_Fail(pGetHistPerHistResult->v_result) )
				{
					logfile_error("Did not get a proper answer result for:",pPropertyInfo->v_identifier);
					Finally();
					return;
				}

				Ov_ForEachChildEx(ov_containment,pGetHistPerHistResult,pKsGetHistResultItem,ksxdrgethist_KsGetHistResultItem){
					if(pKsGetHistResultItem == NULL || Ov_Fail(pKsGetHistResultItem->v_result))
					{
						logfile_error("Did not get a proper answer item for:",pPropertyInfo->v_identifier);
						Finally();
						return;
					}

					if(ov_string_compare(pKsGetHistResultItem->v_identifier,"Tag_res") == OV_STRCMP_EQUAL ||
							ov_string_compare(pKsGetHistResultItem->v_identifier,"Anfangszeit_res") == OV_STRCMP_EQUAL)
					{
						Ov_SetDynamicVectorLength(&tempTimeVec,pKsGetHistResultItem->v_value.value.valueunion.val_string_vec.veclen,TIME);

						for(OV_UINT i = 0;i<pKsGetHistResultItem->v_value.value.valueunion.val_string_vec.veclen;i++){
							for(OV_UINT j = 0;j<strlen(pKsGetHistResultItem->v_value.value.valueunion.val_string_vec.value[i]);j++){
								if(pKsGetHistResultItem->v_value.value.valueunion.val_string_vec.value[i][j] == '-'){
									pKsGetHistResultItem->v_value.value.valueunion.val_string_vec.value[i][j] = '/';
								}
								if(pKsGetHistResultItem->v_value.value.valueunion.val_string_vec.value[i][j] == '.'){
									pKsGetHistResultItem->v_value.value.valueunion.val_string_vec.value[i][j] = '\0';
								}
							}
							ov_time_asciitotime(&tempTimeVec.value[i],pKsGetHistResultItem->v_value.value.valueunion.val_string_vec.value[i]);
						}

						sosx_PropertyInformation_timeStamps_set(Ov_DynamicPtrCast(sosx_PropertyInformation,pPropertyInfo),tempTimeVec.value,tempTimeVec.veclen);
						if(tempTimeVec.veclen >= 1){
							Ov_DynamicPtrCast(sosx_PropertyInformation,pPropertyInfo)->v_validFrom = tempTimeVec.value[0];
							Ov_DynamicPtrCast(sosx_PropertyInformation,pPropertyInfo)->v_validUntil = tempTimeVec.value[tempTimeVec.veclen-1];
						}
					}
					else if(ov_string_compare(pKsGetHistResultItem->v_identifier,"T_Menge_res") == OV_STRCMP_EQUAL ||
							ov_string_compare(pKsGetHistResultItem->v_identifier,"Wert_res") == OV_STRCMP_EQUAL)
					{
						sosx_PropertyInformation_valueVec_set(Ov_DynamicPtrCast(sosx_PropertyInformation,pPropertyInfo),&pKsGetHistResultItem->v_value);
						if(pKsGetHistResultItem->v_value.value.vartype == OV_VT_DOUBLE_VEC){
							Ov_DynamicPtrCast(sosx_PropertyInformation,pPropertyInfo)->v_value.value.vartype = OV_VT_DOUBLE;
							Ov_DynamicPtrCast(sosx_PropertyInformation,pPropertyInfo)->v_value.value.valueunion.val_double = pKsGetHistResultItem->v_value.value.valueunion.val_double_vec.value[0];
						}
					}
					else
					{
						sosx_getKsVal_state_set(pinst, FBCOMLIB_STATE_INTERNAL_ERROR);
						Finally();
						logfile_error("Internal Error: Cannot find the result item:",pPropertyInfo->v_identifier);
						return;
					}
				}
			}

			if(Ov_OK(result)){
				sosx_getKsVal_state_set(pinst, FBCOMLIB_STATE_OK);
				Finally();
				return;
			}
			else
			{
				sosx_getKsVal_state_set(pinst, FBCOMLIB_STATE_INTERNAL_ERROR);
				pinst->v_errorCode = result;
				Finally();
				logfile_error("Internal Error in getHist for:",pPropertyInfo->v_identifier);
				return;
			}
			pinst->v_errorCode = OV_ERR_OK;
		}
		else if(pinstGetHist->p_apiHist.v_status == KSAPI_COMMON_INTERNALERROR)
		{
			sosx_getKsVal_state_set(pinst, FBCOMLIB_STATE_KSAPI_ERROR);
			pinst->v_errorCode = pinstGetHist->p_apiHist.v_result;
			Finally();
			logfile_error("Internal Error in getHist for:",pPropertyInfo->v_identifier);
			return;
		}
		else if(pinstGetHist->p_apiHist.v_status == KSAPI_COMMON_EXTERNALERROR)
		{
			sosx_getKsVal_state_set(pinst, FBCOMLIB_STATE_EXTERNAL_ERROR);
			pinst->v_errorCode = OV_ERR_GENERIC;
			Finally();
			logfile_error("External Error for:",pPropertyInfo->v_identifier);
			return;
		}
		else if(pinstGetHist->p_apiHist.v_status == KSAPI_COMMON_WAITINGFORANSWER)
		{
			if(pltc->secs > (pinst->v_requestSendTime.secs + pinst->v_timeout))
			{
				sosx_getKsVal_state_set(pinst, FBCOMLIB_STATE_TIMEOUT);
				Finally();
				return;
			}
		}
	}

	if((pinst->v_state == FBCOMLIB_STATE_OK) || (pinst->v_state == FBCOMLIB_STATE_INIT))
	{	/*	ready to start	*/
		/*	ksapi-object found	*/
		if(pinst->v_sendRequested)
		{	/*	single send requested	*/
			result = ov_string_setvalue(&(pinstGetHist->p_apiHist.v_serverHost), pinst->v_host);
			if(Ov_Fail(result))
			{
				pinst->v_errorCode = result;
				sosx_getKsVal_state_set(pinst, FBCOMLIB_STATE_INTERNAL_ERROR);
				Finally();
				return;
			}
			result = ov_string_setvalue(&(pinstGetHist->p_apiHist.v_serverName), pinst->v_server);
			if(Ov_Fail(result))
			{
				pinst->v_errorCode = result;
				sosx_getKsVal_state_set(pinst, FBCOMLIB_STATE_INTERNAL_ERROR);
				Finally();
				return;
			}
			result = ov_string_setvalue(&(pinstGetHist->p_apiHist.v_path), pinst->v_path);
			if(Ov_Fail(result))
			{
				pinst->v_errorCode = result;
				sosx_getKsVal_state_set(pinst, FBCOMLIB_STATE_INTERNAL_ERROR);
				Finally();
				return;
			}
		}

		pinstGetHist->p_apiHist.v_holdConnection = TRUE;

		/*	send Requested */
		pVtblGetHist->m_submit(Ov_StaticPtrCast(ksapi_KSApiCommon, &(pinstGetHist->p_apiHist)));

		sosx_getKsVal_state_set(pinst, FBCOMLIB_STATE_WAITING);

		pinst->v_requestSendTime = *pltc;
		pinst->v_sendRequested = FALSE;
		Finally();
		return;
	}
	else if(pinst->v_state != FBCOMLIB_STATE_WRONGINPUT)
	{
		if(pinst->v_retryAfter)
		{
			if(pltc->secs > (pinst->v_requestSendTime.secs + pinst->v_retryAfter))
			{
				if(pinst->v_doReset){
					sosx_getKsVal_doReset_set(pinst, FALSE);
					sosx_getKsVal_doReset_set(pinst, TRUE);
					sosx_getKsVal_doReset_set(pinst, FALSE);
				}
			}
		}
	}
	Finally();
	return;
}

