
/******************************************************************************
 *
 *   FILE
 *   ----
 *   library_open.c
 *
 *   History
 *   -------
 *   2015-04-13   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/

#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx
#endif

#include "sosx.h"
#include "sosxcommon.h"
#include "ov.h"
#include "libov/ov_macros.h"
#include "libov/ov_logfile.h"
#include "libov/ov_path.h"
#include "libov/ov_time.h"
#include "libov/ov_result.h"
#include "libov/ov_library.h"

#ifdef ov_library_open_sosx
#undef ov_library_open_sosx
#endif


/*
 * This function will be called, when the library is loaded.
 * It could generate components and initializes the startup procedure
 */
OV_RESULT ov_library_setglobalvars_sosx_new(void) {
	OV_RESULT							result			= OV_ERR_OK;
	OV_INSTPTR_ov_library				pCaexLib		= NULL;
	OV_INSTPTR_ov_library				pKsapiLib		= NULL;
	OV_INSTPTR_ov_library				pfbcomlib		= NULL;
	OV_INSTPTR_ov_library				pksxdrgethist	= NULL;
	OV_INSTPTR_ov_domain				domain			= NULL;
	OV_INSTPTR_ov_domain				component		= NULL;
	OV_INSTPTR_sosx_executeSimulation	pSimFb			= NULL;

	/*
	 *    set the global variables of the original version
	 *    and if successful, load other libraries
	 *    and create some objects
	 */
	result = ov_library_setglobalvars_sosx();

	/*	check if caex is loaded	*/
	Ov_ForEachChildEx(ov_instantiation, pclass_ov_library, pCaexLib, ov_library)
	{
		if(ov_string_compare(pCaexLib->v_identifier, "caex") == OV_STRCMP_EQUAL)
		{
			break;
		}
	}
	if(!pCaexLib)
	{
		result = Ov_CreateObject(ov_library, pCaexLib, &(pdb->acplt), "caex");
		if(Ov_Fail(result)){
			logfile_error("sosx: Fatal: Couldn't load dependency \"caex\" Reason:", ov_result_getresulttext(result));
			return result;
		}
	}
	/*	check if ksapi is loaded	*/
	Ov_ForEachChildEx(ov_instantiation, pclass_ov_library, pKsapiLib, ov_library)
	{
		if(ov_string_compare(pKsapiLib->v_identifier, "ksapi") == OV_STRCMP_EQUAL)
		{
			break;
		}
	}
	if(!pKsapiLib)
	{
		result = Ov_CreateObject(ov_library, pKsapiLib, &(pdb->acplt), "ksapi");
		if(Ov_Fail(result)){
			logfile_error("sosx: Fatal: Couldn't load dependency \"ksapi\" Reason:", ov_result_getresulttext(result));
			return result;
		}
	}

	/*	check if fbcomlib is loaded	*/
	Ov_ForEachChildEx(ov_instantiation, pclass_ov_library, pfbcomlib, ov_library)
	{
		if(ov_string_compare(pfbcomlib->v_identifier, "fbcomlib") == OV_STRCMP_EQUAL)
		{
			break;
		}
	}
	if(!pfbcomlib)
	{
		result = Ov_CreateObject(ov_library, pfbcomlib, &(pdb->acplt), "fbcomlib");
		if(Ov_Fail(result)){
			logfile_error("sosx: Fatal: Couldn't load dependency \"fbcomlib\" Reason:", ov_result_getresulttext(result));
			return result;
		}
	}

	/*	check if ksxdrgethist is loaded	*/
	Ov_ForEachChildEx(ov_instantiation, pclass_ov_library,pksxdrgethist, ov_library)
	{
		if(ov_string_compare(pksxdrgethist->v_identifier, "ksxdrgethist") == OV_STRCMP_EQUAL)
		{
			break;
		}
	}
	if(!pksxdrgethist)
	{
		result = Ov_CreateObject(ov_library, pksxdrgethist, &(pdb->acplt), "ksxdrgethist");
		if(Ov_Fail(result)){
			logfile_error("sosx: Fatal: Couldn't load dependency \"ksxdrgethist\" Reason:", ov_result_getresulttext(result));
			return result;
		}
	}

	/* create sosx Container */
	domain = (OV_INSTPTR_ov_domain)ov_path_getobjectpointer("/TechUnits", 2);
	result = Ov_CreateObject(ov_domain, component, domain, "sosx");
	if(Ov_Fail(result) &&  result != OV_ERR_ALREADYEXISTS){
		logfile_error("Fatal: Couldn't create Object 'sosx' reason:", ov_result_getresulttext(result));
		return result;
	} else {
		result = OV_ERR_OK;
	}

	/* create sosx management Container */
	domain = (OV_INSTPTR_ov_domain)ov_path_getobjectpointer("/TechUnits", 2);
	result = Ov_CreateObject(ov_domain, component, domain, "sosxMngmt");
	if(Ov_Fail(result) &&  result != OV_ERR_ALREADYEXISTS){
		logfile_error("Fatal: Couldn't create Object 'sosxMngmt' reason:", ov_result_getresulttext(result));
		return result;
	} else {
		result = OV_ERR_OK;
	}

	/* create execute simulation fb */
	domain = (OV_INSTPTR_ov_domain)ov_path_getobjectpointer("/TechUnits/sosxMngmt", 2);
	result = Ov_CreateObject(sosx_executeSimulation, pSimFb, domain, "executeSimulation");
	if(Ov_Fail(result) &&  result != OV_ERR_ALREADYEXISTS){
		logfile_error("Fatal: Couldn't create Object 'executeSimulation' reason:", ov_result_getresulttext(result));
		return result;
	} else {
		result = OV_ERR_OK;
	}
	fb_task_actimode_set(Ov_DynamicPtrCast(fb_task,pSimFb),0);

	return result;
}
/*
 *       Replace the 'setglobalvars' function of a library with this
 *       previous one, which additionally creates instances.
 * 	This is called by the OV system upon library load.
 */
OV_DLLFNCEXPORT OV_LIBRARY_DEF *ov_library_open_sosx(void) {
	/* local variables */
	static OV_LIBRARY_DEF *OV_LIBRARY_DEF_sosx_new;
	/*
	 *       replace the 'setglobalvars' function created by the code generator
	 *       with a new one.
	 */
	OV_LIBRARY_DEF_sosx_new = ov_library_open_sosx_old();
	OV_LIBRARY_DEF_sosx_new->setglobalvarsfnc = ov_library_setglobalvars_sosx_new;
	return OV_LIBRARY_DEF_sosx_new;
}
