
/******************************************************************************
 *
 *   FILE
 *   ----
 *   workflowManagement.c
 *
 *   History
 *   -------
 *   2016-08-18   File created
 *
 *******************************************************************************
 *
 *   This file is generated by the 'acplt_builder' command
 *
 ******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_sosx
#define OV_COMPILE_LIBRARY_sosx


#include "workflowManagement.h"
#include "informationModelManagement.h"


#if OV_SYSTEM_NT
#include  "io.h"
#endif

#if !OV_SYSTEM_NT
#include <unistd.h>
#endif

/********
 * importCAEXFile - This function loads XML-CAEX files into OV
 * and creates a CAEX object structure in /TechUnits/ImportExport/CAEX.
 * This is done in two steps:
 * 1. The XML file is transformed into a FBD file. This done outside of OV
 * using the xalan Tool
 * 2. The FBD file is loaded into the OV server
 * @param DirPath - Path to the directory that contains the XML files
 * @param FileList - list of all XML files
 * @return
 */
OV_DLLFNCEXPORT OV_RESULT sosx_workflowManagement_importCaexFile(
		OV_STRING							DirPath,
		OV_STRING_VEC 						FileList
){

	OV_INSTPTR_ov_object					pCAEX				= NULL;
	OV_INSTPTR_ksxdr_xdrManagerCom			pManagerCom			= NULL;

	OV_STRING								tmpstr				= NULL;
	OV_STRING								fbdPath				= NULL;
	OV_STRING								xalanPath			= NULL;
	OV_STRING								filePath			= NULL;
	OV_STRING								cmd					= NULL;
	OV_STRING								confDir				= NULL;

	OV_STRING_VEC							confDirList			= {0,NULL};

	OV_UINT									index				= 1;
	OV_INT									systemResult		= 2;

	OV_ANY									ServerName			= {};

	OV_RESULT								result				= OV_ERR_OK;

#undef Finally
#define Finally()											\
		/* do not free tmpstr */							\
		ov_string_setvalue(&fbdPath,NULL);					\
		ov_string_setvalue(&xalanPath,NULL);				\
		ov_string_setvalue(&filePath,NULL);					\
		ov_string_setvalue(&cmd,NULL);						\
		ov_string_setvalue(&confDir,NULL);					\
		Ov_SetAnyValue(&ServerName,NULL);					\
		if(confDirList.veclen>0){							\
			ov_string_freelist(confDirList.value);			\
		confDirList.veclen = 0;}							\

	/* get the pointer of the caex container */
	pCAEX = ov_path_getobjectpointer("/TechUnits/ImportExport/CAEX",2);
	if (!(pCAEX)){
		log_error("Cannot find domain 'CAEX'");
		Finally();
		return OV_ERR_GENERIC;
	}

	/***********************************
	 * Step 1. convert XML to FBD
	 * 1. get xalanPath form confDirPath
	 * 2. check if file is already loaded
	 * 3. if file is not loaded jet create command for XML-FBD conversion
	 * 4. execute command
	 ******/

	// confDir = .\ACPLTdev\AcpltDevelopmentKit\acplt\servers\MANAGER
	// xalanPath = .\AcpltDevelopmentKit\acplt\dev\caex\CAEX2OVXI

	ov_memstack_lock();
	confDir = ov_vendortree_getcmdlineoption_value("CONFDIR");

	if (ov_string_compare(confDir,NULL)==OV_STRCMP_EQUAL){
		log_error("Cannot find the 'CONFDIR' of the Server.");
		Finally();
		return OV_ERR_GENERIC;
	}

	// get path until \acplt
	confDirList.value = ov_string_split(confDir,"\\",&confDirList.veclen);
	ov_string_setvalue(&xalanPath,confDirList.value[0]);
	while(ov_string_compare(confDirList.value[index],"servers") != OV_STRCMP_EQUAL && index < confDirList.veclen){
		ov_string_append(&xalanPath,"\\");
		ov_string_append(&xalanPath,confDirList.value[index]);
		index++;
	}
	ov_memstack_unlock();
	if(ov_string_compare(confDirList.value[index],"acplt")==OV_STRCMP_EQUAL){
		log_error("'CONFDIR' Path is worng. Can not find the xalan tool.");
		Finally();
		return OV_ERR_GENERIC;
	}

	// add missing path to xalan tool
	ov_string_append(&xalanPath,"\\dev\\caex\\CAEX2OVXI");

	for(OV_UINT i = 0; i < FileList.veclen ; i++){
		/* check if file name is valid */
		if(!ov_string_match(FileList.value[i],"*.xml") && !ov_string_match(FileList.value[i],"*.export") && !ov_string_match(FileList.value[i],"*.SimRes")){
			logfile_error("filename is invalid ",FileList.value[i]);
			continue;
		}

		/* check if file is already loaded */
		if (NULL != Ov_SearchChildEx(ov_containment,Ov_DynamicPtrCast(ov_domain,pCAEX),FileList.value[i],caex_CAEXFile)){
			logfile_error("file is already loaded ",FileList.value[i]);
			continue;
		}

		/* create filePath */
		ov_string_setvalue(&filePath,DirPath);

#if OV_SYSTEM_NT
		/* check if folder exists  */
		if( _access(filePath , 00 ) == -1 ) {
			/* file does not exist */
			logfile_error("Cannot find the folder",DirPath);
			Finally();
			return OV_ERR_BADPATH;
		}
#endif

#if !OV_SYSTEM_NT
		/* check if folder exists  */
		if( access(filePath , 00 ) == -1 ) {
			/* file does not exist */
			logfile_error("Cannot find the folder",DirPath);
			Finally();
			return OV_ERR_BADPATH;
		}
#endif

		ov_string_append(&filePath,"\\");
		ov_string_append(&filePath,FileList.value[i]);

#if OV_SYSTEM_NT
		/* check if XML file exists  */
		if( _access(filePath , 00 ) == -1 ) {
			/* file does not exist */
			logfile_error("Cannot find the XML file",FileList.value[i]);
			continue;
		}
#endif

#if !OV_SYSTEM_NT
		/* check if XML file exists  */
		if( access(filePath , 00 ) == -1 ) {
			/* file does not exist */
			logfile_error("Cannot find the XML file",FileList.value[i]);
			continue;
		}
#endif

		/* create fbdPath */
		ov_string_setvalue(&fbdPath,filePath);
		tmpstr = strrchr(fbdPath,'.');
		*tmpstr = '\0';
		tmpstr=NULL;
		ov_string_append(&fbdPath,".fbd");

#if OV_SYSTEM_NT
		if( _access(fbdPath , 00 ) != -1 ) {
			/* fbd file already  exists -> delete file  */
			if (remove(fbdPath) != 0){
				logfile_error("Could not remove the fbd-file",FileList.value[i]);
				continue;
			}
		}
#endif
#if !OV_SYSTEM_NT
		if( access(fbdPath , 00 ) != -1 ) {
			/* fbd file already  exists -> delete file  */
			if (remove(fbdPath) != 0){
				logfile_error("Could not remove the fbd-file",FileList.value[i]);
				continue;
			}
		}
#endif

		/* convert XML file to FBD file */
		/* create command: C:\\...\\AcpltDevelopmentKit\\acplt\\dev\\caex\\CAEX2OVXI\\xalan -o  C:\\...\\xml\\BaseLibrary.fbd C:\\...\\xml\\BaseLibrary.xml  C:\\...\\AcpltDevelopmentKit-win\\AcpltDevelopmentKit\\acplt\\dev\\caex\\CAEX2OVXI\\CAEX2FBD.xsl*/
		ov_string_setvalue(&cmd,xalanPath);
		ov_string_append(&cmd,"\\xalan -o ");
		ov_string_append(&cmd,fbdPath);
		ov_string_append(&cmd," ");
		ov_string_append(&cmd,filePath);
		ov_string_append(&cmd," ");
		ov_string_append(&cmd,xalanPath);
		ov_string_append(&cmd,"\\CAEX2FBD.xsl");

		/* executed cmd - convert xml->fbd */
		systemResult = system(cmd);
		ov_string_setvalue(&cmd,NULL);

#if OV_SYSTEM_NT
		/* check if conversion was successful */
		if(systemResult != 0 || _access(fbdPath, 00 ) == -1 ) {
			/* file does not exists */
			logfile_error("Conversion failed ", FileList.value[i]);
			continue;
		}
#endif

#if !OV_SYSTEM_NT
		/* check if conversion was successful */
		if(systemResult != 0 || access(fbdPath, 00 ) == -1 ) {
			/* file does not exists */
			logfile_error("Conversion failed ", FileList.value[i]);
			continue;
		}
#endif
		pManagerCom = (OV_INSTPTR_ksxdr_xdrManagerCom)ov_path_getobjectpointer("/communication/ksxdr/ManagerCom",2);
		if(pManagerCom == NULL){
			logfile_error("Failed to get Port", "");
			return result;
		}

		result = ov_vendortree_getservername(&ServerName,NULL);
		if(Ov_Fail(result)){
			return result;
			logfile_error("Failed to get server name ", "");
		}

		/* load FBD file */
		/* create command */
		ov_string_setvalue(&cmd,"start fb_dbcommands -s ");
		ov_string_append(&cmd,"localhost:");
		ov_string_append(&cmd,pManagerCom->v_ManagerPort);
		ov_string_append(&cmd,"/");
		ov_string_append(&cmd,ServerName.value.valueunion.val_string);

		ov_string_append(&cmd," -f ");
		ov_string_append(&cmd,fbdPath);
		ov_string_append(&cmd," -load");

		/* execute cmd - load fbd into server */
		systemResult = system(cmd);
		ov_string_setvalue(&cmd,NULL);
	}
	Finally();
	return result;
}

/**
 * exportCaexFile - This function exports a SoSX structure as a CAEX-XML file.
 * This is done in two steps.
 * 1. A CAEX structure is created in /TechUnits/ImportExport/CAEX
 * 2. The CAEX structure is exported as an CAEX-XML-file
 * @param pElementToBeRead
 * @param FilePath
 * @return
 */
OV_DLLFNCEXPORT OV_RESULT sosx_workflowManagement_exportCaexFile(
		OV_INSTPTR_ov_domain				pElementToBeRead,
		OV_STRING							FilePath,
		OV_STRING							FileName,
		OV_BOOL								exportStateOnly
){
	OV_RESULT							result		= OV_ERR_OK;

	OV_INSTPTR_ov_domain				pTarget		= NULL;
	OV_INSTPTR_caex_CAEXFile			pCaexStruct	= NULL;
	OV_INSTPTR_caex_CAEXXMLExporter		pExporter	= NULL;
	OV_INSTPTR_ov_domain				pdomain		= NULL;
	OV_INSTPTR_sosx_executeSimulation	pexeSim		= NULL;

	OV_STRING							tempStr		= NULL;
	OV_STRING							caexPath	= NULL;
	OV_STRING							Name		= NULL;

#undef Finally
#define Finally()															\
		ov_string_setvalue(&tempStr,NULL);									\
		ov_string_setvalue(&caexPath,NULL);									\
		ov_string_setvalue(&Name,NULL);										\
		/* delete caex structure after writing xml file */					\
		if(pCaexStruct){													\
			result = Ov_DeleteObject(pCaexStruct);							\
			if(Ov_Fail(result)){											\
				log_error("Could not delete the CAEX export structure.");	\
			}																\
		}																	\

	/* find caex container */
	pTarget = Ov_DynamicPtrCast(ov_domain,ov_path_getobjectpointer("/TechUnits/ImportExport/CAEX",2));
	if (!(pTarget)){
		log_error("Cannot find domain 'CAEX'");
		Finally();
		return OV_ERR_GENERIC;
	}

	if(pElementToBeRead == NULL){
		log_error("Could not find the SoSX element.");
		result = OV_ERR_GENERIC;
		Finally();
		return result;
	}

	if(ov_string_compare(FileName,"") != OV_STRCMP_EQUAL){
		/* construct CAEX export structure name*/
		ov_string_setvalue(&tempStr,FileName);
		ov_string_append(&tempStr,".export");
	}
	else
	{
		ov_string_setvalue(&tempStr,pElementToBeRead->v_identifier);
		ov_string_append(&tempStr,".export");
	}
	ov_string_setvalue(&Name,tempStr);

	/* Try to find the executeSimulation FB an transfer the last filename used */
	pdomain = (OV_INSTPTR_ov_domain)ov_path_getobjectpointer("/TechUnits/sosxMngmt", 2);
	if(pdomain){
		Ov_ForEachChildEx(ov_containment,pdomain,pexeSim,sosx_executeSimulation){

			if(ov_string_compare(pexeSim->v_lastFileName,"") == OV_STRCMP_EQUAL || ov_string_compare(pexeSim->v_CeaxArchiveDir,FilePath) == OV_STRCMP_EQUAL){
				sosx_executeSimulation_lastFileName_set(pexeSim,Name);
				sosx_executeSimulation_CeaxArchiveDir_set(pexeSim,FilePath);
			}
		}
	}

	/* check if CAEX export structure already exists */
	if(Ov_SearchChildEx(ov_containment,pTarget,tempStr,caex_CAEXFile)){
		log_error("CAEX-export structure already exists.");
		result = OV_ERR_GENERIC;
		Finally();
		return result;
	}

	log_info("Creating CEAX object structure");

	/* read SoSX model and create CAEX structure*/
	result = sosx_workflowManagement_readElement(pElementToBeRead,pTarget,TRUE,Name,exportStateOnly);
	if(Ov_Fail(result)){
		log_error("Could not read the SoSX element.");
		Finally();
		return result;
	}

	log_info("CEAX object structure created");


	/* find created caex structure */
	pCaexStruct = Ov_SearchChildEx(ov_containment,pTarget,tempStr,caex_CAEXFile);
	if(!pCaexStruct){
		log_error("Could not find the CAEX export structure.");
		result = OV_ERR_GENERIC;
		Finally();
		return result;
	}

	/* get path of caex structure */
	ov_memstack_lock();
	ov_string_setvalue(&caexPath,ov_path_getcanonicalpath(Ov_DynamicPtrCast(ov_object,pCaexStruct),2));
	ov_memstack_unlock();
	if(!caexPath){
		log_error("Failed to get the path to the CAEX export structure.");
		result = OV_ERR_GENERIC;
		Finally();
		return result;
	}

	/* export XML */
	/* create CAEXXMLExporter object
	 * first check if Exporter object already exists */
	pExporter = Ov_SearchChildEx(ov_containment,pTarget,"tempExporter",caex_CAEXXMLExporter);
	if(!pExporter){
		result = Ov_CreateObject(caex_CAEXXMLExporter,pExporter,pTarget,"tempExporter");
		if(Ov_Fail(result)){
			log_error("Could not create the CAEXXMLExporter.");
			Finally();
			return result;
		}
	}

	/* set input values for CAEXXMLExporter */
	ov_string_setvalue(&pExporter->v_OutputPath,FilePath);
	ov_string_setvalue(&pExporter->v_RootFile,caexPath);

	/* write XML file */
	result = caex_CAEXXMLExporter_writeXMLFile_set(pExporter,TRUE);
	if(Ov_Fail(result)){
		log_error("Could not read the SoSX element.");
		Finally();
		return result;
	}

	/* delete Exporter object */
	result = Ov_DeleteObject(pExporter);
	if(Ov_Fail(result)){
		log_error("Could not delete the CAEXXMLExporter.");
		Finally();
		return result;
	}

	Finally();
	return result;
}

/*
 * exportCaex
 */

OV_DLLFNCEXPORT OV_RESULT sosx_workflowManagement_exportCaexCyclic(
		OV_STRING							ElementToBeRead,
		OV_STRING							FilePath,
		OV_TIME_SPAN						cyctime
){
	OV_RESULT 						result		= OV_ERR_OK;
	OV_INSTPTR_ov_domain			pCaex		= NULL;
	OV_INSTPTR_sosx_exportCaexFb	pExFb		= NULL;


	pCaex = Ov_DynamicPtrCast(ov_domain,ov_path_getobjectpointer("/TechUnits/ImportExport/CAEX",2));

	pExFb = Ov_SearchChildEx(ov_containment,pCaex,"cyclicCaexExport",sosx_exportCaexFb);
	if(pExFb == NULL){
		result = Ov_CreateObject(sosx_exportCaexFb,pExFb,pCaex,"cyclicCaexExport");
		if(Ov_Fail(result)){
			return result;
		}
	}

	if(pExFb->v_actimode == 0){
		pExFb->v_cyctime = cyctime;

		ov_string_setvalue(&pExFb->v_source,ElementToBeRead);
		ov_string_setvalue(&pExFb->v_target,FilePath);

		pExFb->v_iexreq = 1;
		pExFb->v_actimode = 1;

	}else{
		pExFb->v_actimode = 0;
	}

	return result;
}

/********
 * create and configure a fb for the execution of the simulation
 * activate it afterwards
 */

OV_DLLFNCEXPORT OV_RESULT sosx_workflowManagement_executeSimulationCyclic(
		OV_STRING							pathToSimDir,
		OV_STRING							pathToSimResDir,
		OV_STRING							pathToCeaxArchiveDir,
		OV_STRING							SosxStruct,
		OV_TIME_SPAN						cycTimeSec
) {

	OV_INSTPTR_ov_domain				domain 		= NULL;
	OV_RESULT							result 		= OV_ERR_OK;
	OV_INSTPTR_sosx_executeSimulation	pSimFb 		= NULL;
	OV_TIME								now	   		= {0,0};
	OV_TIME								nextExeT	= {0,0};

	/* create or find if already exists */
	domain = (OV_INSTPTR_ov_domain)ov_path_getobjectpointer("/TechUnits/sosxMngmt", 2);
	result = Ov_CreateObject(sosx_executeSimulation, pSimFb, domain, "executeSimulation");
	if(Ov_Fail(result) &&  result != OV_ERR_ALREADYEXISTS){
		logfile_error("Fatal: Couldn't create Object 'executeSimulation' reason:", ov_result_getresulttext(result));
		return result;
	} else {
		pSimFb = Ov_SearchChildEx(ov_containment,domain,"executeSimulation",sosx_executeSimulation);
		result = OV_ERR_OK;
	}
	if(!pSimFb){
		return OV_ERR_GENERIC;
	}

	/* configure */
	ov_string_setvalue(&pSimFb->v_SimDir,pathToSimDir);
	ov_string_setvalue(&pSimFb->v_CeaxArchiveDir,pathToCeaxArchiveDir);
	ov_string_setvalue(&pSimFb->v_SimResDir,pathToSimResDir);
	ov_string_setvalue(&pSimFb->v_SosxStruct,SosxStruct);

	ov_time_gettime(&now);
	ov_time_add(&nextExeT,&now,&cycTimeSec);

	fb_task_proctime_set(Ov_DynamicPtrCast(fb_task,pSimFb),&nextExeT);

	fb_task_cyctime_set(Ov_DynamicPtrCast(fb_task,pSimFb),&cycTimeSec);

	/* activate */
	fb_task_actimode_set(Ov_DynamicPtrCast(fb_task,pSimFb),1);

	return OV_ERR_OK;
}

/*************************************************************
 * getLibraryList creates an array containing pointers to all libraries of the InternalElement
 *************************************************************/

OV_DLLFNCEXPORT OV_RESULT sosx_workflowManagement_getLibraryList(
		OV_INSTPTR_caex_CAEXBasicObject 		pCaexElement,
		OV_INSTPTR_caex_CAEXObject				**pLibList,
		OV_UINT									*LenLibList
){
	OV_RESULT								result				= OV_ERR_OK;
	OV_INSTPTR_caex_RoleRequirements		pRoleRequirements	= NULL;
	OV_INSTPTR_ov_domain					pSearchIn			= NULL;
	OV_INSTPTR_ov_domain					pCaexLibrary		= NULL;
	OV_STRING								pRefPath			= NULL;
	OV_STRING								pRefClass			= NULL;


#undef	Finally
#define Finally() \
		ov_string_setvalue(&pRefPath,NULL); 	\
		ov_string_setvalue(&pRefClass,NULL); 	\


	if(pCaexElement == NULL){
		log_error("Cannot find the InternalElement");
		result = OV_ERR_GENERIC;
		Finally();
		return result;
	}

	/* get path to the Role or SystemUnit */
	Ov_ForEachChildEx(ov_containment,pCaexElement,pRoleRequirements,caex_RoleRequirements){
		ov_string_setvalue(&pRefClass,Ov_DynamicPtrCast(caex_InternalElement, pCaexElement)->v_Name);
		ov_string_setvalue(&pRefPath,pRoleRequirements->v_RefBaseRoleClassPath);
	}
	if (pRefPath == NULL){
		if(Ov_CanCastTo(caex_InternalElement,pCaexElement)){
			ov_string_setvalue(&pRefClass,Ov_DynamicPtrCast(caex_InternalElement, pCaexElement)->v_Name);
			ov_string_setvalue(&pRefPath,Ov_DynamicPtrCast(caex_InternalElement, pCaexElement)->v_RefBaseSystemUnitPath);
		}
		if (Ov_CanCastTo(caex_SystemUnitClass,pCaexElement)){
			ov_string_setvalue(&pRefClass,Ov_DynamicPtrCast(caex_SystemUnitClass, pCaexElement)->v_Name);
			ov_string_setvalue(&pRefPath,Ov_DynamicPtrCast(caex_SystemUnitClass, pCaexElement)->v_RefBaseClassPath);
		}
		if (Ov_CanCastTo(caex_RoleClass,pCaexElement)){
			ov_string_setvalue(&pRefClass,Ov_DynamicPtrCast(caex_RoleClass, pCaexElement)->v_Name);
			ov_string_setvalue(&pRefPath,Ov_DynamicPtrCast(caex_RoleClass, pCaexElement)->v_RefBaseClassPath);
		}
	}

	if(pRefClass == NULL){
		logfile_error("InternalElement has no RefClass ", pCaexElement->v_identifier);
		result = OV_ERR_GENERIC;
		Finally();
		return result;
	}

	*pLibList = (OV_INSTPTR_caex_CAEXObject*)Ov_HeapRealloc(*pLibList,sizeof(OV_INSTPTR_caex_CAEXObject));
	*pLibList[0] = Ov_DynamicPtrCast(caex_CAEXObject,pCaexElement);
	pSearchIn = Ov_DynamicPtrCast(ov_domain,pCaexElement);

	while((ov_string_compare(pRefClass, "System")				!=OV_STRCMP_EQUAL) &&
			(ov_string_compare(pRefClass, "Process")			!=OV_STRCMP_EQUAL) &&
			(ov_string_compare(pRefClass, "Port")				!=OV_STRCMP_EQUAL) &&
			(ov_string_compare(pRefClass, "SourceSink")			!=OV_STRCMP_EQUAL) &&
			(ov_string_compare(pRefClass, "DistributionNode")	!=OV_STRCMP_EQUAL) &&
			(ov_string_compare(pRefClass, "Property")			!=OV_STRCMP_EQUAL) &&
			(ov_string_compare(pRefClass, "PropertyInformation")!=OV_STRCMP_EQUAL) &&
			(ov_string_compare(pRefClass, "Stream")				!=OV_STRCMP_EQUAL)){

		if(pSearchIn == NULL || pRefPath == NULL){
			logfile_error("Cannot resolve the library path of ", pCaexElement->v_identifier);
			result = OV_ERR_GENERIC;
			Finally();
			return result;
		}

		/* check library */

		result = findLibrary(&pRefPath,pSearchIn,&pCaexLibrary);
		if(Ov_Fail(result)){
			logfile_error("Cannot find the library of ", pCaexElement->v_identifier);
			result = OV_ERR_GENERIC;
			Finally();
			return result;
		}
		(*LenLibList)++;

		*pLibList = (OV_INSTPTR_caex_CAEXObject*)Ov_HeapRealloc(*pLibList, ((*LenLibList) +1) * sizeof(OV_INSTPTR_caex_CAEXObject));

		if (Ov_CanCastTo(caex_SystemUnitClass,pCaexLibrary)){
			ov_string_setvalue(&pRefClass,Ov_DynamicPtrCast(caex_SystemUnitClass,pCaexLibrary)->v_Name);
			ov_string_setvalue(&pRefPath,(Ov_DynamicPtrCast(caex_SystemUnitClass,pCaexLibrary))->v_RefBaseClassPath);
			(*pLibList)[*LenLibList] =  Ov_DynamicPtrCast(caex_CAEXObject,pCaexLibrary);
		} else
			if (Ov_CanCastTo(caex_RoleClass,pCaexLibrary)){
				ov_string_setvalue(&pRefClass,Ov_DynamicPtrCast(caex_RoleClass,pCaexLibrary)->v_Name);
				ov_string_setvalue(&pRefPath,(Ov_DynamicPtrCast(caex_RoleClass, pCaexLibrary))->v_RefBaseClassPath);
				(*pLibList)[*LenLibList] = Ov_DynamicPtrCast(caex_CAEXObject,pCaexLibrary);
			}

		pSearchIn = pCaexLibrary;
	}

	/*Clear memory*/
	Finally();
	return result;
}



/**
 * @param pElementToBeUpdated - Pointer to the element that will be updated
 * @param pUpdate - pointer to the InternalElement that specifies the Update
 * @return
 */
OV_DLLFNCEXPORT OV_RESULT sosx_workflowManagement_updateElement(
		OV_INSTPTR_ov_domain				pElementToBeUpdated,
		OV_INSTPTR_caex_CAEXBasicObject		pUpdate,
		SOSX_UPDATE_TYPE					updateType
){
	OV_RESULT								result			= OV_ERR_OK;
#undef Finally
#define Finally()

	if (pElementToBeUpdated == NULL || pUpdate == NULL){
		log_error("ElementToBeUpdated and/or Update not found!");
		result = OV_ERR_GENERIC;
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_SoSContainer,pElementToBeUpdated)){
		sosx_workflowManagement_updateSoSContainer(Ov_DynamicPtrCast(sosx_SoSContainer,pElementToBeUpdated),Ov_DynamicPtrCast(caex_CAEXFile,pUpdate),updateType);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_System,pElementToBeUpdated)){
		sosx_workflowManagement_updateSystem(Ov_DynamicPtrCast(sosx_System,pElementToBeUpdated),Ov_DynamicPtrCast(caex_CAEXObject,pUpdate),updateType);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_Process,pElementToBeUpdated)){
		sosx_workflowManagement_updateProcess(Ov_DynamicPtrCast(sosx_Process,pElementToBeUpdated),Ov_DynamicPtrCast(caex_CAEXObject,pUpdate),updateType);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_Port,pElementToBeUpdated)){
		sosx_workflowManagement_updatePort(Ov_DynamicPtrCast(sosx_Port,pElementToBeUpdated),Ov_DynamicPtrCast(caex_CAEXObject,pUpdate),updateType);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_SourceSink,pElementToBeUpdated) && !Ov_CanCastTo(sosx_DistributionNode,pElementToBeUpdated)){
		sosx_workflowManagement_updateSourceSink(Ov_DynamicPtrCast(sosx_SourceSink,pElementToBeUpdated),Ov_DynamicPtrCast(caex_CAEXObject,pUpdate),updateType);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_DistributionNode,pElementToBeUpdated)){
		sosx_workflowManagement_updateDistributionNode(Ov_DynamicPtrCast(sosx_DistributionNode,pElementToBeUpdated),Ov_DynamicPtrCast(caex_CAEXObject,pUpdate),updateType);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_Property,pElementToBeUpdated)){
		sosx_workflowManagement_updateProperty(Ov_DynamicPtrCast(sosx_Property,pElementToBeUpdated),Ov_DynamicPtrCast(caex_CAEXObject,pUpdate),updateType);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_PropertyInformation,pElementToBeUpdated)){
		sosx_workflowManagement_updatePropertyInformation(Ov_DynamicPtrCast(sosx_PropertyInformation,pElementToBeUpdated),Ov_DynamicPtrCast(caex_CAEXObject,pUpdate),updateType);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_Stream,pElementToBeUpdated)){
		/* Do nothing Streams are updated by StreamHandler objects
		 * sosx_workflowManagement_updateStream(Ov_DynamicPtrCast(sosx_Stream,pElementToBeUpdated),Ov_DynamicPtrCast(caex_CAEXObject,pUpdate),updateType);
		 */
		Finally();
		return result;
	}

	logfile_error("can not read object - unknown object class", pElementToBeUpdated->v_identifier);
	result = OV_ERR_GENERIC;
	Finally();
	return result;
}

/**
 *
 * @param pElementToBeRead - pointer to the object that shall be read
 * @param pTarget - pointer to the container in which the CAEX structure will be stored
 * @param writeHeader - set to true if a CAEX Header should be written
 * @return OV_RESULT Error level
 */
OV_DLLFNCEXPORT OV_RESULT sosx_workflowManagement_readElement(
		OV_INSTPTR_ov_domain					pElementToBeRead,
		OV_INSTPTR_ov_domain					pTarget,
		OV_BOOL								writeHeader,
		OV_STRING								HeaderName,
		OV_BOOL								readStateOnly
){
	OV_RESULT								result			= OV_ERR_OK;
	OV_INSTPTR_sosx_SoSContainer			pSoS			= NULL;

#undef	Finally
#define Finally()							\

#define undoReadInCaseOfError(result, pTarget, pElementToBeRead)											\
		/* check if error occurred and delete object in case of Ov_Fail*/ 									\
		if(Ov_Fail(result)){																				\
			if(Ov_SearchChild(ov_containment, pTarget, pElementToBeRead->v_identifier) != NULL){			\
				Ov_DeleteObject(Ov_SearchChild(ov_containment, pTarget, pElementToBeRead->v_identifier));	\
			}																								\
		}																									\

	if (pElementToBeRead == NULL || pTarget == NULL){
		log_error("ElementToBeRead or Target not found!");
		result = OV_ERR_GENERIC;
		Finally();
		return result;
	}

		if(!Ov_CanCastTo(sosx_sosxdomain,pElementToBeRead)){
			Finally();
			return OV_ERR_BADOBJTYPE;
		}

		if(readStateOnly &&
				Ov_DynamicPtrCast(sosx_sosxdomain,pElementToBeRead)->v_includeInStateFile == FALSE){
			Finally();
			return result;
		}

		if(writeHeader){
			result = createCAEXHeader(pElementToBeRead,pTarget,HeaderName,readStateOnly);
			if(Ov_Fail(result)){
				log_error("could not create the CAEX Header");
				Finally();
				return result;
			}
			Finally();
			return result;
		}
		if(Ov_CanCastTo(sosx_SoSContainer,pElementToBeRead)){
			pSoS = Ov_DynamicPtrCast(sosx_SoSContainer,pElementToBeRead);
			result = sosx_informationModelManagement_readSoSContainer(Ov_DynamicPtrCast(sosx_SoSContainer,pElementToBeRead),pTarget,readStateOnly);
			undoReadInCaseOfError(result, pTarget, pElementToBeRead);
			Finally();
			return result;
		}
		if(Ov_CanCastTo(sosx_System,pElementToBeRead)){
			result = sosx_informationModelManagement_readSystem(Ov_DynamicPtrCast(sosx_System,pElementToBeRead),pTarget,readStateOnly);
			undoReadInCaseOfError(result, pTarget, pElementToBeRead);
			Finally();
			return result;
		}
		if(Ov_CanCastTo(sosx_Process,pElementToBeRead)){
			result = sosx_informationModelManagement_readProcess(Ov_DynamicPtrCast(sosx_Process,pElementToBeRead),pTarget,readStateOnly);
			undoReadInCaseOfError(result, pTarget, pElementToBeRead);
			Finally();
			return result;
		}
		if(Ov_CanCastTo(sosx_Port,pElementToBeRead)){
			result = sosx_informationModelManagement_readPort(Ov_DynamicPtrCast(sosx_Port,pElementToBeRead),pTarget,readStateOnly);
			undoReadInCaseOfError(result, pTarget, pElementToBeRead);
			Finally();
			return result;
		}
		if(Ov_CanCastTo(sosx_DistributionNode,pElementToBeRead)){
			result = sosx_informationModelManagement_readDistributionNode(Ov_DynamicPtrCast(sosx_DistributionNode,pElementToBeRead),pTarget,readStateOnly);
			undoReadInCaseOfError(result, pTarget, pElementToBeRead);
			Finally();
			return result;
		}
		if(Ov_CanCastTo(sosx_SourceSink,pElementToBeRead)){
			result = sosx_informationModelManagement_readSourceSink(Ov_DynamicPtrCast(sosx_SourceSink,pElementToBeRead),pTarget,readStateOnly);
			undoReadInCaseOfError(result, pTarget, pElementToBeRead);
			Finally();
			return result;
		}
		if(Ov_CanCastTo(sosx_Property,pElementToBeRead)){
			result = sosx_informationModelManagement_readProperty(Ov_DynamicPtrCast(sosx_Property,pElementToBeRead),pTarget,readStateOnly);
			undoReadInCaseOfError(result, pTarget, pElementToBeRead);
			Finally();
			return result;
		}
		if(Ov_CanCastTo(sosx_PropertyInformation,pElementToBeRead)){
			result = sosx_informationModelManagement_readPropertyInformation(Ov_DynamicPtrCast(sosx_PropertyInformation,pElementToBeRead),pTarget,readStateOnly);
			undoReadInCaseOfError(result, pTarget, pElementToBeRead);
			Finally();
			return result;
		}
		if(Ov_CanCastTo(sosx_Stream,pElementToBeRead)){
			result = sosx_informationModelManagement_readStream(Ov_DynamicPtrCast(sosx_Stream,pElementToBeRead),pTarget,readStateOnly);
			undoReadInCaseOfError(result, pTarget, pElementToBeRead);
			Finally();
			return result;
		}
		if(Ov_CanCastTo(sosx_FileMonitor,pElementToBeRead)){
			// do nothing
			return result;
		}
		logfile_error("can not read object - unknown object class", pElementToBeRead->v_identifier);
		result = OV_ERR_GENERIC;
		Finally();
		return result;
}

/**
 * deleteElement - This function "deletes" any given SOSX Object.
 * (validUntil is set to NOW)
 * @param pElementToBeDeleted - pointer to the object that shall be deleted
 * @return OV_RESULT error level if the function fails to delete an object.
 */
OV_DLLFNCEXPORT OV_RESULT sosx_workflowManagement_deleteElement(
		OV_INSTPTR_ov_domain				pElementToBeDeleted
){
	OV_RESULT								result			= OV_ERR_OK;


#undef	Finally
#define Finally()

	if (pElementToBeDeleted == NULL){
		log_error("Element to be deleted not found!");
		result = OV_ERR_GENERIC;
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_SoSContainer,pElementToBeDeleted)){
		result = sosx_informationModelManagement_deleteSoSContainer(Ov_DynamicPtrCast(sosx_SoSContainer,pElementToBeDeleted));
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_System,pElementToBeDeleted)){
		result = sosx_informationModelManagement_deleteSystem(Ov_DynamicPtrCast(sosx_System,pElementToBeDeleted));
		Finally();
		return result;
	}
	if(Ov_CanCastTo(sosx_Process,pElementToBeDeleted)){
		result = sosx_informationModelManagement_deleteProcess(Ov_DynamicPtrCast(sosx_Process,pElementToBeDeleted));
		Finally();
		return result;
	}
	if(Ov_CanCastTo(sosx_Port,pElementToBeDeleted)){
		result = sosx_informationModelManagement_deletePort(Ov_DynamicPtrCast(sosx_Port,pElementToBeDeleted));
		Finally();
		return result;
	}
	if(Ov_CanCastTo(sosx_DistributionNode,pElementToBeDeleted)){
		result = sosx_informationModelManagement_deleteDistributionNode(Ov_DynamicPtrCast(sosx_DistributionNode,pElementToBeDeleted));
		Finally();
		return result;
	}
	if(Ov_CanCastTo(sosx_SourceSink,pElementToBeDeleted)){
		result = sosx_informationModelManagement_deleteSourceSink(Ov_DynamicPtrCast(sosx_SourceSink,pElementToBeDeleted));
		Finally();
		return result;
	}
	if(Ov_CanCastTo(sosx_Property,pElementToBeDeleted)){
		result = sosx_informationModelManagement_deleteProperty(Ov_DynamicPtrCast(sosx_Property,pElementToBeDeleted));
		Finally();
		return result;
	}
	if(Ov_CanCastTo(sosx_Stream,pElementToBeDeleted)){
		// nothing to do here. Streams can only be by their StreamHandler
		Finally();
		return result;
	}
	if(Ov_CanCastTo(sosx_PropertyInformation,pElementToBeDeleted)){
		result = sosx_informationModelManagement_deletePropertyInformation(Ov_DynamicPtrCast(sosx_PropertyInformation,pElementToBeDeleted));
		Finally();
		return result;
	}

	logfile_error("can not delete object - unknown object class", pElementToBeDeleted->v_identifier);
	result = OV_ERR_GENERIC;
	Finally();
	return result;
}

/**
 * validateElement - This function validates any SOSX object
 * @param pTargetElement - pointer to the object that shall be validated
 * @param pValidationLog - pointer to the validation log that will be extended if an error is found
 * @return OV_RESULT error level if function fails to validate the object
 */
OV_DLLFNCEXPORT OV_RESULT sosx_workflowManagement_validateElement(
		OV_INSTPTR_ov_domain				pTargetElement,
		OV_STRING_VEC						*pValidationLog
){
	OV_RESULT								result			= OV_ERR_OK;

#undef Finally
#define Finally()

	if (pTargetElement == NULL){
		log_error("Element to be validated not found!");
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_SoSContainer,pTargetElement)){
		result = sosx_informationModelManagement_validateSoSContainer(Ov_DynamicPtrCast(sosx_SoSContainer,pTargetElement),pValidationLog);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_System,pTargetElement)){
		sosx_informationModelManagement_validateSystem(Ov_DynamicPtrCast(sosx_System,pTargetElement),pValidationLog);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_Process,pTargetElement)){
		sosx_informationModelManagement_validateProcess(Ov_DynamicPtrCast(sosx_Process,pTargetElement),pValidationLog);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_Port,pTargetElement)){
		sosx_informationModelManagement_validatePort(Ov_DynamicPtrCast(sosx_Port,pTargetElement),pValidationLog);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_DistributionNode,pTargetElement)){
		sosx_informationModelManagement_validateDistributionNode(Ov_DynamicPtrCast(sosx_DistributionNode,pTargetElement),pValidationLog);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_SourceSink,pTargetElement) && !Ov_CanCastTo(sosx_DistributionNode,pTargetElement)){
		sosx_informationModelManagement_validateSourceSink(Ov_DynamicPtrCast(sosx_SourceSink,pTargetElement),pValidationLog);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_Property,pTargetElement)){
		sosx_informationModelManagement_validateProperty(Ov_DynamicPtrCast(sosx_Property,pTargetElement),pValidationLog);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_PropertyInformation,pTargetElement)){
		sosx_informationModelManagement_validatePropertyInformation(Ov_DynamicPtrCast(sosx_PropertyInformation,pTargetElement),pValidationLog);
		Finally();
		return result;
	}

	if(Ov_CanCastTo(sosx_Stream,pTargetElement)){
		sosx_informationModelManagement_validateStream(Ov_DynamicPtrCast(sosx_Stream,pTargetElement),pValidationLog);
		Finally();
		return result;
	}

	extendValidationLog(pValidationLog,"Error","can not validate object - unknown object class",Ov_DynamicPtrCast(sosx_sosxdomain,pTargetElement));
	Finally();
	return result;
}

/**
 * createElement - transforms a CAEX-InternalElement to a SOSX-Element.
 * @param pTargetElement - Element in which the new element will be created
 * @param pElement - pointer to the CEAX-InternalElement that specifies the new Element
 * @return - the result of element creation (OV_RESULT)
 */
OV_DLLFNCEXPORT OV_RESULT sosx_workflowManagement_createElement(
		OV_INSTPTR_ov_domain				pTargetElement,
		OV_INSTPTR_caex_CAEXBasicObject		pElement
){
	OV_INSTPTR_caex_CAEXObject			*pLibList			= NULL;
	OV_STRING							pRefClass			= NULL;
	OV_UINT								LenLibList			= 0;
	OV_RESULT							result				= OV_ERR_OK;

#undef	Finally
#define Finally() 									\
		ov_string_setvalue(&pRefClass,NULL); 		\
		ov_free(pLibList);							\

	if (!(pElement)){
		log_error("InternalElement not found!");
		result = OV_ERR_BADPARAM;
		Finally();
		return result;
	}
	/* create SoSContainer if pElement is of type CAEXFile */
	if (Ov_CanCastTo(caex_CAEXFile, pElement)){
		result = sosx_workflowManagement_createSoSContainer(Ov_DynamicPtrCast(ov_domain,pTargetElement),Ov_DynamicPtrCast(caex_CAEXFile,pElement));
		Finally();
		return result;
	}

	/* get base class type e.g. system, process, port, SourceSink ...
	 * InternalElement can either instantiate a SystemUnitClass or a RoleClass
	 */
	result = sosx_workflowManagement_getLibraryList(Ov_DynamicPtrCast(caex_CAEXBasicObject,pElement),&pLibList,&LenLibList);
	if (Ov_Fail(result)){
		logfile_error("Cannot resolve the library path of ", pElement->v_identifier);
		Finally();
		return result;
	}

	if (!(Ov_DynamicPtrCast(caex_CAEXObject,pLibList[LenLibList]))){
		logfile_error("Cannot resolve the library path of ", pElement->v_identifier);
		result = OV_ERR_GENERIC;
		Finally();
		return result;
	}

	ov_string_setvalue(&pRefClass,(Ov_DynamicPtrCast(caex_CAEXObject,pLibList[LenLibList]))->v_Name);

	if (!pRefClass){
		logfile_error("InternalElement does not instantiate a Role or SystemUnitClass",pElement->v_identifier);
		result = OV_ERR_GENERIC;
		Finally();
		return result;
	}

	/* interpret the reference class of Element and create the right object*/
	if (ov_string_compare(pRefClass, "System")==OV_STRCMP_EQUAL){
		result = sosx_workflowManagement_createSystem(Ov_DynamicPtrCast(ov_domain,pTargetElement),Ov_DynamicPtrCast(caex_InternalElement,pElement));
		Finally();
		return result;
	}
	if (ov_string_compare(pRefClass, "Alternative")==OV_STRCMP_EQUAL){
		result = sosx_workflowManagement_createAlternative(Ov_DynamicPtrCast(sosx_System,pTargetElement),Ov_DynamicPtrCast(caex_InternalElement,pElement));
		Finally();
		return result;
	}
	if (ov_string_compare(pRefClass, "SourceSink")==OV_STRCMP_EQUAL){
		result = sosx_workflowManagement_createSourceSink(Ov_DynamicPtrCast(sosx_SoSContainer,pTargetElement),Ov_DynamicPtrCast(caex_InternalElement,pElement));
		Finally();
		return result;
	}
	if (ov_string_compare(pRefClass, "DistributionNode")==OV_STRCMP_EQUAL){
		result = sosx_workflowManagement_createDistributionNode(Ov_DynamicPtrCast(sosx_System,pTargetElement),Ov_DynamicPtrCast(caex_InternalElement,pElement));
		Finally();
		return result;
	}
	if (ov_string_compare(pRefClass, "Port")==OV_STRCMP_EQUAL){
		result = sosx_workflowManagement_createPort(Ov_DynamicPtrCast(sosx_DetailedElement,pTargetElement),Ov_DynamicPtrCast(caex_InternalElement,pElement));
		Finally();
		return result;
	}
	if (ov_string_compare(pRefClass, "Process")==OV_STRCMP_EQUAL){
		result = sosx_workflowManagement_createProcess(Ov_DynamicPtrCast(sosx_System,pTargetElement),Ov_DynamicPtrCast(caex_InternalElement,pElement));
		Finally();
		return result;
	}
	if (ov_string_compare(pRefClass, "Stream")==OV_STRCMP_EQUAL){
		result = sosx_workflowManagement_createStream(Ov_DynamicPtrCast(ov_domain,pTargetElement),Ov_DynamicPtrCast(caex_InternalElement,pElement));
		Finally();
		return result;
	}
	if (ov_string_compare(pRefClass, "PropertyInformation")==OV_STRCMP_EQUAL){
		result = sosx_workflowManagement_createPropertyInformation(Ov_DynamicPtrCast(sosx_Property,pTargetElement),Ov_DynamicPtrCast(caex_InternalElement, pElement));
		Finally();
		return result;
	}
	if (ov_string_compare(pRefClass, "Property")==OV_STRCMP_EQUAL){
		result = sosx_workflowManagement_createProperty(Ov_DynamicPtrCast(sosx_DetailedElement,pTargetElement),Ov_DynamicPtrCast(caex_InternalElement,pElement));
		Finally();
		return result;
	}
	result = OV_ERR_GENERIC;
	logfile_error("InternalElement does not instantiate a base class of the information model",pElement->v_identifier);
	Finally();
	return result;
}

#endif
